### ISSUE TITLE
Opening Draw Desktop causes two instances to be opened

### ISSUE THREAD

**Issue by bt-tech-dd** [jgraph/drawio-desktop#860] opened 2022-01-03 14:11 UTC
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
When opening Draw.io two instances are opened.

**To Reproduce**
1. Click the Start Menu
2. Click on Draw.io
3. Two instances of Draw.io are opened

**Expected behavior**
Expected behavior is for only one instance to be opened.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 16.1.2

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
I first noticed after performing an automatic upgrade from version 15. I then tried uninstalling and reinstalling but the issue was still occurring.

**Comment by mararad** [comment] 2022-01-04 12:08
Is it possible to attach a video showing all the performed steps and the result, please?
I couldn't reproduce this at my place.

Thanks,

**Comment by bt-tech-dd** [comment] 2022-01-04 13:29
This is a video of what is happening.
https://user-images.githubusercontent.com/68382967/148066072-f6214e89-1408-4e00-a3a9-9302d92d203c.mp4

**Comment by davidjgraph** [comment] 2022-01-04 13:52
Which release binary do you have installed? There's not 2 installs somehow?

**Comment by bt-tech-dd** [comment] 2022-01-04 14:11
When I performed the uninstall and reinstall I used the file from the following link to reinstall.

https://github.com/jgraph/drawio-desktop/releases/download/v16.1.2/draw.io-16.1.2-windows-installer.exe

Wouldn't an uninstall have gotten rid of all copies? How would a Start Menu shortcut point to two different installations?

Also, if I go to the main executable file, C:\Program Files\draw.io\draw.io.exe, and double click on that, the same problem occurs.

**Comment by ericmillinder** [comment] 2022-01-04 20:46
I am seeing the same thing. It started happening after an update from 15 to 16. 

If I remove the appdata/Roaming/draw.io, only one instance opens at startup. 
If I restore the original appdata/Roaming/draw.io, 2 windows open again at startup.

**Comment by martini5468** [comment] 2022-01-05 13:21
I did notice this behaviour when updating from 15 to 16 as well. One thing I have is turn off "Show Start Screen". If I turn it on I see the prompt to create new/open existing and no 2nd instance starts. Without that prompt I get a 2nd instance launched.

Another observation is the 2nd instance appears to be the online version not a 2nd desktop instance (if that makes sense). As noted by @ericmillinder when removing the appdata folder the behaviour is resolved. However if I turn off the "Show Start Screen" option and restart draw.io I have the same issue with 2 instances starting.

**Comment by yuylyp** [comment] 2022-01-06 03:35
hi guys,
I encounter same issue.
if I enable "show start screen", there is only one window.
if disabled, there are two windows.

**Comment by davidjgraph** [comment] 2022-01-06 07:08
Thanks for the feedback. Let's not have any more "me too" or "+1", unless you add information that provides debugging information.

**Comment by Metal-666** [comment] 2022-01-06 15:30
This also happens when using Microsoft Store version of the app (sorry if this is not useful info)

**Comment by davidjgraph** [comment] 2022-01-27 20:53
Fixed in v16.4.11

**Closed as completed by davidjgraph** 2022-01-27 20:53 UTC
