### ISSUE TITLE
The startup dialogue does not close after selecting Create New Diagram or Open Existing Diagram

### ISSUE THREAD

**Issue by b1506704** [jgraph/drawio-desktop#1470] opened 2023-09-26 23:36 UTC
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
The issue occurs in latest version 21.8.2, when the startup dialogue does not close after selecting Create New Diagram or Open Existing Diagram.

**To Reproduce**
1. Open Draw.io desktop.
2. Click on either Create New Diagram or Open Existing Diagram.
3. Draw.io file successfully created/opened but the startup dialogue still not close.

**Expected behavior**
The startup dialogue should close after selecting Create New Diagram or Open Existing Diagram.

**Screenshots**
![image](https://github.com/jgraph/drawio-desktop/assets/60655387/5a8f38b1-0075-4e94-99e9-7238d8d314f7)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 21.8.2

**Desktop (please complete the following information):**
 - OS: Windows 11 Education with latest update.

**Additional context**
I believe the version before 21.8.2 is working correctly without this issue. There must be something wrong with the new release.

**Comment by Rainmaker52** [comment] 2023-09-28 10:02
Workaround: you can open a dialog by using Windows explorer and doubleclicking the item as long as you have the file associations setup.

It only does not work when you open draw.io and selecting "Open an existing diagram".

**Comment by davidjgraph** [comment] 2023-09-28 13:30
Try 22.0.0. We can't reproduce it, but there's a change in the core in dialog ordering which is likely related to this.

**Comment by Rainmaker52** [comment] 2023-09-28 15:25
22.0 is... different.

I'm now getting this behavior:
- Clicking "New" hides the dialog
- The "unsaved document" popup comes up
- The dialog New/Open re-appears

If I don't have "unsaved documents", the buttons now work as expected.

So, it's probably related to the "Select a draft" dialog.

**Comment by b1506704** [comment] 2023-09-28 17:42
Agree with @Rainmaker52 . After upgrading to 22.0, if I start Draw.io desktop, and if there's a draft available to select, the dialogue "Select a draft to continue ..." will appear. If I cancel it and select open exist diagram instead, the startup dialogue reappears again. However, this time I'm able to close it with X button.

**Comment by davidjgraph** [comment] 2023-09-28 17:59
OK, we'll create a new issue and take a look since the status of the issue depends on the initial report.

What I'm more interested in is the steps you're following to get a draft. How are so many people loading with a draft unsaved? Do you kill -9 the app to close it....

**Comment by Rainmaker52** [comment] 2023-09-28 19:04
Just shutting down while draw.io is open should be enough.

I think this happened by Windows deciding it was time to update, without giving me any say in whether or not it should reboot.

I've had the dialog ever since, but never really cared enough to pay attention to it.

**Comment by davidjgraph** [comment] 2023-10-02 20:24
Please try 22.0.1.

**Comment by b1506704** [comment] 2023-10-06 13:14
The issue I mentioned above is fixed in 22.0.1. Thanks.

**Closed as completed** 2023-10-06 13:26 UTC
Labels: bug
