### ISSUE TITLE
Locked process consuming high CPU

### ISSUE THREAD

**Issue by epomatti** [jgraph/drawio-desktop#1076] opened 2022-08-02 12:58 UTC
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
Frequently the Draw.io process keeps running on high CPU. Even if I close the window, it still keeps locked. I have to kill it manually in the task manager to solve it.

I was not able to find a way to reproduce the issue. It currently happens randomly and around once every day.

![image](https://user-images.githubusercontent.com/6530769/182379289-e4136b5d-1d81-4451-9d35-c23c30387316.png)

Only workaround is to kill the process manually.

- draw.io version 19.0.3

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
Not sure if related but I frequently work on files that are in my local OneDrive sync folders.
I also use Dark Mode.

**Comment by xBoo** [comment] 2022-08-03 07:46
I also have this problem and the process doesn't close automatically when I close the program

**Comment by xBoo** [comment] 2022-08-03 07:50
> 

I figured out that the problem might really be related to OneDrive, I'm using OneDrive in the same situation as you

**Comment by brets1001** [comment] 2022-08-16 14:28
I have the same problem. My files are not stored on OneDrive (although do i have OneDrive drives, can't see how it could be related). Whenever i open an additional instance of Draw.io, one new process appear. The picture show 3 high-consuming process after i just opened 4 files. 

I can kill those processes at any time without effect of draw.io. But they don't disappear when i close draw.io, i always have to kill them manually.

I run diagrams.net 20.2.3 desktop on windows 10 Pro 21H2 64-bit.
![DrawIO high consuming processes](https://user-images.githubusercontent.com/111368481/184904838-9b3c28c8-52fe-4eb6-a2d9-279455c8c8a1.png)

**Comment by mannisp** [comment] 2022-08-29 12:21
I have the same problem: I am using Windows 10 (21H1), and the latest drawio Windows client version, 20.2.3
The problem is reproducible:
After restarting Windows I open one drawio diagram, CPU load is normal (<1 % standby).
Then I open second diagram, and CPU load for that process is ~15 % and remains. Each new opened diagram consumes high CPU load until after ~9 diagrams CPU consumption is almost maxed out.
Even after closing the diagrams, the processes are left running, and they have to be ended in Task manager.

In the earlier reports it was speculated whether this problem is related to Onedrive. Well, I have Onedrive, as probably all Windows users, but I don't open these files from Onedrive since they are on local hard drive, so I don't think just the existence of Onedrive in my computer has anything to do with the problem.

![kuva](https://user-images.githubusercontent.com/66009928/187199296-0f3a35e4-f901-46a3-96dd-8d4d9bd642c3.png)

**Comment by mannisp** [comment] 2022-08-29 16:53
Note: This is the same bug that has been previously reported as issue 390: Heavy CPU load from draw.io windows client.
I have further comments there.

**Comment by howff** [comment] 2022-09-04 12:31
I frequently have this problem and it's still an issue with the latest version
![draw io_usage](https://user-images.githubusercontent.com/3064316/188313552-d95fedbd-c7fe-472a-9a73-6b2a763c9edb.PNG)
(that's with no visible draw.io windows open!)

See also #390

**Comment by mannisp** [comment] 2022-09-21 13:40
**I just updated to version 20.3.0 and the problem is GONE!**
I tested in two computers that right before update the problem existed, and after installing update 20.3.0 there was no additional draw.io background processes consuming CPU anymore.

**Comment by epomatti** [comment] 2022-09-21 14:15
@mannisp I'm also at `20.3.0` for a while and haven't noticed issues, but I haven't been using it as much.

I'll use it for a while more and report it here in some time, maybe then we can close the issue.

**Closed as completed** 2022-10-11 21:23 UTC
