### ISSUE TITLE
How to restore orignal file by XX.drawio.bkp?

### ISSUE THREAD

**Issue by suyu15** [jgraph/drawio-desktop#1206] opened 2023-01-03 08:30 UTC
After saving, I found that there were more temporary files. When I opened them again, I was asked to choose whether to edit or discard them. I chose to edit, save them, and then close them. When I opened it again, it was not saved. Now how do I restore my work? I only have a drawio.bkp file in my hand.
Can you help me restore my work?
[mysql.drawio.bkp](https://github.com/BinLee218/suyu/blob/main/~%24mysql.drawio.bkp)

**Comment by davidjgraph** [comment] 2023-01-03 12:18
Duplicate of #1205

**Closed as completed by davidjgraph** 2023-01-03 12:18 UTC
