### ISSUE TITLE
Allow association of specific file suffix on macOS and Window

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/drawio-desktop#35] opened 2018-04-24 20:16 UTC
https://github.com/atom/atom/blob/d6d47c422c07b71421471720f7d96b52890feeb0/resources/mac/atom-Info.plist#L745-L761

https://github.com/atom/atom/blob/d6d47c422c07b71421471720f7d96b52890feeb0/src/browser/squirrel-update.coffee#L90-L92

**Comment by davidjgraph** [comment] 2018-08-14 22:38
The key problem we have with this one is draw.io is a web application, firstly. In browsers the content type wins. On desktop file suffix wins. We get a lot of problems with users mixing the two environments, and there's no way to do both well.

In the browser, the main workaround for when users switch to a computer is to create a .html file that already has a file association to a browser and can open the correct page from that html wrapper.

That said, the desktop is more heavily used than we expected. But people need to vote for this.

**Comment by KyleStay** [comment] 2018-08-14 22:57
The key problem with .xml is that it's often associated with other programs. Using a custom extension would have no effect on the web version, it's still xml/html, it just has a different extension and could be associated with the browser. All it would do is all users to associate it with desktop versions of draw.io. It could also potentially allow draw.io to implement a service handler like gmail does in Chrome.

I believe all that needs to done is allow users to set the default extension to something custom, preferably a standard endorsed by draw.io. Currently I'm just manually setting the extension .drawio when I save each and every file which is quite tedious and frustrating.

Figma has balanced desktop and web very successfully with the .fig files they use. They are a great example of what users are looking for.

**Comment by KyleStay** [comment] 2018-08-14 22:59
How do I vote for this?

**Comment by KyleStay** [comment] 2018-08-17 02:58
I created a pull request the implements my desired functionality and goes deeper into why I think this change is important: https://github.com/jgraph/drawio/pull/303

Please let me know if you have any questions or if I could be of further assistance.

**Comment by ksix** [comment] 2019-05-15 04:54
Is #11 the same thing?

**Comment by alderg** [comment] 2019-05-30 04:55
Duplicate of #11

**Comment by ashrafteleb** [comment] 2019-06-04 12:12
Added, should be available with the next release

**Closed by ashrafteleb** 2019-06-04 12:12 UTC
Labels: enhancement

**Comment by davidjgraph** [comment] 2019-06-05 16:49
https://github.com/jgraph/drawio-desktop/releases/tag/v10.7.5
