### ISSUE TITLE
Background not shown in pdf exports

### ISSUE THREAD

**Issue by ksiansf** [jgraph/drawio-desktop#811] opened 2021-12-02 07:39 UTC
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When I export a drawing to PDF the background pages are not shown 

**To Reproduce**
1. Create a new diagram
2. Click on the plus sign to add a page (Page-2)
3. Drag a rectangle onto Page-2
4. Go back to Page-1
5. Click the Change button next to background (select Page-2 as background for Page-1)
6. In the dropdown for the second radio button select Page-2
7. Click Apply
8. Go to File -> Export as -> PDF
9. Click Export
10. Click Save
11. Open the resulting PDF file

**Expected behavior**
The background page should also show in the pdf 

- draw.io version [e.g. 15.4.0]
 - OS: [e.g. Win10]

**Comment by ksiansf** [comment] 2021-12-02 10:53
I was using the Desktop version. I also tested last version 15.8.7 and the issue is still there.
I notice that on the online version it works, but I cannot use it because then I get an error that the size of the diagram is too big.

**Comment by fernandolcx** [comment] 2022-01-12 15:27
duplicate of #713

**Closed as completed** 2022-01-12 15:41 UTC
