### ISSUE TITLE
“Copy as image” copies all elements on the page instead of copying the selection

### ISSUE THREAD

**Issue by hard-sign** [jgraph/drawio-desktop#537] opened 2021-03-27 19:08 UTC
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The “copy as image” menu item copies all the contents of a page as an image.

**To Reproduce**
1. Create a new diagram
2. Draw a rectangle
3. Draw a circle
4. Select the rectangle
5. Right-click on the selection and choose “copy as image”
6. Open a text processor (e. g. OnlyOffice)
7. Create a new document and press Ctrl+V (paste). You’ll see both rectangle and circle.

**Expected behavior**
I want to see just the rectangle, i. e. only the selected items.

**draw.io version (In the Help->About menu of the draw.io editor):**
14.5.1

**Desktop (please complete the following information):**
➜ uname -a
Linux penguin 5.4.0-40-generic jgraph/drawio#44~18.04.1-Ubuntu SMP Wed Jun 24 23:13:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
➜ lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

No browser, it’s the desktop version.

**Comment by alderg** [comment] 2021-03-29 08:03
Duplicate of 535

**Comment by davidjgraph** [comment] 2021-03-29 08:09
Duplicate of #535

**Closed as completed by davidjgraph** 2021-03-29 08:09 UTC
