### ISSUE TITLE
Error while updating: ENOENT no such file or directory

### ISSUE THREAD

**Issue by gldhnchn** [jgraph/drawio-desktop#349] opened 2020-08-04 13:40 UTC
After opening drawio, it informs me that there is an update available.
![update dialog](https://user-images.githubusercontent.com/24368572/89299921-b717fe80-d667-11ea-95ae-24d04067bf15.png)
After clicking on OK, I'll get the following error message:
> Downloading draw.io update...
> Error occurred while fetching updates. Error: ENOENT: no such file or directory, open '/opt/draw.io/resources/app-update.yml'

![error message](https://user-images.githubusercontent.com/24368572/89300219-27268480-d668-11ea-8a42-6afb5b4a2448.png)
This message will stay there and nothing happens. The error message is right, there is no /opt/draw.io/resources/app-update.yml' file on my system. I'm running draw.io 13.5.1, which was installed from the deb package of the [release page](https://github.com/jgraph/drawio-desktop/releases). My system is Ubuntu 20.04. The terminal gives me the following output:
```
15:41:52.126 › Checking for update
15:41:52.916 › Found version 13.5.7 (url: draw.io-x86_64-13.5.7.AppImage)
15:41:52.917 › @update-available@
 {
  version: '13.5.7',
  files: [
    {
      url: 'draw.io-x86_64-13.5.7.AppImage',
      sha512: 'B/86AyIgN78EznZsyPmnlzFLHMhqbI1TWX6B5iEBQRwhrroqh3Et2MRllK4o4GBC5a0lrabtqPCRMPD3gskhWw==',
      size: 107621177,
      blockMapSize: 113485
    }
  ],
  path: 'draw.io-x86_64-13.5.7.AppImage',
  sha512: 'B/86AyIgN78EznZsyPmnlzFLHMhqbI1TWX6B5iEBQRwhrroqh3Et2MRllK4o4GBC5a0lrabtqPCRMPD3gskhWw==',
  releaseDate: '2020-07-30T22:37:21.007Z',
  releaseName: '13.5.7',
  releaseNotes: '<h2>Releases Notes for 13.5.7</h2>\n' +
    '<p><a href="https://github.com/jgraph/drawio-desktop/releases/download/v13.5.7/draw.io-13.5.7-windows-installer.exe">Windows Installer</a><br>\n' +
    '<a href="https://github.com/jgraph/drawio-desktop/releases/download/v13.5.7/draw.io-13.5.7-windows-no-installer.exe">Windows No Installer</a><br>\n' +
    '<a href="https://github.com/jgraph/drawio-desktop/releases/download/v13.5.7/draw.io-13.5.7.dmg">macOS</a><br>\n' +
    'Linux - <a href="https://github.com/jgraph/drawio-desktop/releases/download/v13.5.7/draw.io-amd64-13.5.7.deb">deb</a>, <a href="https://snapcraft.io/drawio" rel="nofollow">snap</a>, <a href="https://github.com/jgraph/drawio-desktop/releases/download/v13.5.7/draw.io-x86_64-13.5.7.AppImage">AppImage</a> or <a href="https://github.com/jgraph/drawio-desktop/releases/download/v13.5.7/draw.io-x86_64-13.5.7.rpm">rpm</a><br>\n' +
    '<a href="https://chrome.google.com/webstore/detail/drawio-desktop/pebppomjfocnoigkeepgbmcifnnlndla/reviews" rel="nofollow">Google Chrome OS</a></p>\n' +
    '<p><strong>ChangeLog:</strong></p>\n' +
    '<ul>\n' +
    '<li>Updates to <a href="https://github.com/jgraph/drawio/blob/v13.5.7/ChangeLog">draw.io 13.5.7</a>, changes from, and including, 13.5.2 to 13.5.7 are new in this desktop release.</li>\n' +
    '</ul>'
} null
15:41:55.041 › Downloading update from draw.io-x86_64-13.5.7.AppImage
15:41:55.056 › Error: Error: ENOENT: no such file or directory, open '/opt/draw.io/resources/app-update.yml'
15:41:55.057 › @error@
 Error: ENOENT: no such file or directory, open '/opt/draw.io/resources/app-update.yml'
(node:19182) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/opt/draw.io/resources/app-update.yml'
(node:19182) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:19182) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by davidjgraph** [comment] 2020-08-04 16:05
Duplicate of https://github.com/jgraph/drawio-desktop/issues/138

**Closed by davidjgraph** 2020-08-04 16:05 UTC
