### ISSUE TITLE
Command line export does not wait until end of operation before exiting

### ISSUE THREAD

**Issue by ivanli** [jgraph/drawio-desktop#135] opened 2019-08-01 22:32 UTC
When running draw.io executable with `--export` to png, the command exits before the file is generated. This is not ideal when using the command in a CI environment, where in the next step, I would go ahead and consume the generated.

**Comment by ashrafteleb** [comment] 2019-08-02 02:31
We are using Node.js fs.writeFileSync which should wait until file is written before moving to the next step where we return and exit.

Also, I tested a basic bash script (below) and it worked well (the generated file is moved from Downloads to Documents).

draw.io --export /Users/xyz/Downloads/Test.drawio -f png
mv /Users/xyz/Downloads/Test.drawio.png /Users/xyz/Documents/

Please provide the script, environment, and more details on how to reproduce.

**Comment by ivanli** [comment] 2019-08-05 20:05
Thanks for looking into this. My environment:

OS: Win10
Shell: command prompt with admin privileges
Draw.IO version: v10.9.5

```batch
draw.io --export path\to\file.drawio --border=10 -f png
move path\to\file.drawio.png .\
```

Results in: `The system cannot find the file specified.` on the move command.

**Comment by ashrafteleb** [comment] 2019-08-07 13:08
The error is in the output file name, it is file.png instead of file.drawio.png

The following works for me in the same environment

`draw.io --export path\to\file.drawio --border=10 -f png`
`move path\to\file.png .\`

**Closed** 2019-08-07 16:25 UTC

**Comment by ivanli** [comment] 2019-08-16 02:40
That's super strange... executing `draw.io --export path\to\file.drawio --border=10 -f png` definitely generates a file at `path\to\file.drawio.png` and not what you observed. 

Is there a way to get any debug logging to find out what's going on?

**Comment by ashrafteleb** [comment] 2019-08-16 11:31
With every exported file, a message is printed to the console showing the converted file or an error if the conversion failed

E.g,
path\to\file.drawio -> path\to\file.drawio.png

Another option to ensure output file name is to use -o 

E.g,

draw.io --export path\to\file.drawio --border=10 -o path\to\file.png

If you want to debug more, you can check out the project and run it with NODE_ENV=development

**Comment by ArthurAttout** [comment] 2023-01-04 13:35
I'm not sure why this issue is closed. 
Still happens with 20.7.4 under Windows 10 

Trying to export a diagram with Powershell using DrawIO CLI returns immediatly, then prints the export info later (like 1.5 second after) :

```
PS C:\Users\200207121\source\repos\opus_swad> draw.io.exe -x -f pdf -o build\cover_page.pdf my_diagram.drawio
PS C:\Users\200207121\source\repos\opus_swad>
source\frontpage_temp.xml -> build\cover_page.pdf
```

I have to put `sleep` functions after every call to DrawIO because the file is not guaranteed to exist after the command returns ..
