### ISSUE TITLE
alt keys don't work for opening the menu

### ISSUE THREAD

**Issue by wadsworj** [jgraph/drawio-desktop#841] opened 2021-12-21 13:00 UTC
trying to use this as I don't use a keyboard/mouse and was finding the web version difficult to use.
I use voice dictation so keyboard shortcuts are really important.

alt keys don't work for opening the menu

example, "alt-v" should open the "View" menu, but it doesn't.

**Comment by davidjgraph** [comment] 2021-12-21 14:46
Could try the voice plugin, https://www.diagrams.net/doc/faq/voice-plugin , nobody ever really used it that we know of though, so might have rotted.

**Comment by wadsworj** [comment] 2021-12-21 15:26
that's cool! but really just what I would like is standard shortcut keys to work, nothing specific for voice just normal shortcut keys

**Comment by davidjgraph** [comment] 2021-12-23 11:52
Duplicate of #710

**Closed as completed by davidjgraph** 2021-12-23 11:52 UTC
Labels: feature request
