### ISSUE TITLE
macOS Monterey and drawio-desktop file picker is not opening when exporting a diagram

### ISSUE THREAD

**Issue by anksos** [jgraph/drawio-desktop#796] opened 2021-11-23 10:16 UTC
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

Describe the bug
This issue is linked with this https://github.com/jgraph/drawio-desktop/issues/767 after updating to 15.7.3 was working fine without issue, but after 12 days stopped working.

To Reproduce

    Open a diagram
    File -> Export as -> .png
    Click export

Expected behavior
Expectation is to open the file picker and give you the possibility to select destination and name of the outcome file. I have checked any export options none of them working.

Screenshots
N/A

draw.io version (In the Help->About menu of the draw.io editor):

draw.io version v15.7.3

Desktop (please complete the following information):

macOS Monterey version 12.0.1

Additional context
This was working fine after i updated to 15.7.3 but then suddenly stopped working. Online when I go to the app.diagrams.net is working the export function without any issue. 
I have checked also the permissions of draw.io desktop app for my files and the App has permissions to see the filesystem.

**Comment by m-mohamedin** [comment] 2021-12-30 13:45
We couldn't reproduce, but we made a change on how the dialog is open. Please try the next version 16.1.2 (soon will be released) and let us know if it still has the problem.

**Closed as completed** 2022-01-05 14:38 UTC
Labels: blocked/need-info
