### ISSUE TITLE
option to change storage location on desktop version

### ISSUE THREAD

**Issue by wsavran** [jgraph/drawio-desktop#1235] opened 2023-02-13 23:48 UTC
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the solution you'd like**
An equivalent dialogue in the "File > Save-as" and "File > Open-from" menus for the desktop application to change the storage location would be helpful. I prefer using the desktop application, and being able to work on diagrams locally and in the cloud (eg., Google Drive) would be a welcome change.

**Describe alternatives you've considered**
Currently, this can be done through the web-based application, but not possible (as far as I can tell) within the desktop application.

**Additional context**

Screenshots from Web application 

***Web-application File > Open-from menu***
<img width="490" alt="Screen Shot 2023-02-13 at 3 43 54 PM" src="https://user-images.githubusercontent.com/35315438/218599793-e8275c93-ca98-4817-93a5-f9c20132e464.png">

***Web-application File > Save-as***
<img width="481" alt="image" src="https://user-images.githubusercontent.com/35315438/218599443-0f95dfd9-5305-4d93-96e5-0a71f2c72327.png">

**Comment by davidjgraph** [comment] 2023-02-14 04:13
Duplicate of #950

**Closed as completed by davidjgraph** 2023-02-14 04:13 UTC
