### ISSUE TITLE
White screen when pasting an image on Windows 10

### ISSUE THREAD

**Issue by Code-Dei-Tech** [jgraph/drawio-desktop#855] opened 2021-12-28 15:24 UTC
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
The draw.io program turns into a white screen and becomes unresponsive when I paste an image. I had to crash the draw.io application from task manager to close it.

**To Reproduce**
[Issue.zip](https://github.com/jgraph/drawio-desktop/files/7785304/Issue.zip)
1. Extract 'SES.drawio' from 'Issue.zip'
2. Open 'SES.drawio'
3. Copy one of the images
4. Keep pasting the same image on the board

**Expected behavior**
The diagram should be a mix of many images and text. If much memory is needed for the program to work, it should draw more from the CPU memory.

**Screenshots**
![image](https://user-images.githubusercontent.com/64435179/147580358-e1862420-186f-447b-b5b8-f285bb230ff5.png)
![image](https://user-images.githubusercontent.com/64435179/147580407-fe957373-3e94-4c39-9ca9-62b5d786ec68.png)

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 16.0.2

**Desktop (please complete the following information):**
 - Windows 10 Home Build 19042.1415 x64

**Additional context**
I need to create Draw.io diagrams that are heavy with images and access them offline; it is much preferred to use the desktop app than the browser.

**Comment by davidjgraph** [comment] 2021-12-28 18:57
Duplicate of #853

**Closed as completed by davidjgraph** 2021-12-28 18:57 UTC
