### ISSUE TITLE
copy and paste are not working with mapped keys in macOS Desktop Version 13.5.7

### ISSUE THREAD

**Issue by michalkz** [jgraph/drawio-desktop#358] opened 2020-08-12 17:35 UTC
I have 'ctrl' assigned to 'cmd' and 'cmd' assigned to 'ctrl' on external keyboard
ctrl+c and ctrl+v is not working until I press 'cmd' once, after typing some txt it will stop working again
ctrl+z and ctrl+d are working correctly

**Comment by ashrafteleb** [comment] 2020-08-20 00:41
Duplicate of https://github.com/jgraph/drawio-desktop/issues/2

**Closed by ashrafteleb** 2020-08-20 00:41 UTC
