### ISSUE TITLE
font issue when saving or loading file

### ISSUE THREAD

**Issue by ybrhue** [jgraph/drawio-desktop#413] opened 2020-10-28 10:28 UTC
Snap 13.7.9 (latest) on latest manjaro with plasma.

See:

![image](https://user-images.githubusercontent.com/35401453/97424155-9bdc2880-1910-11eb-8dd5-e06582335e15.png)

**Comment by mararad** [comment] 2020-10-28 12:28
Hi, 

we don't support manjaro (never tested it) so unfortunately, there is nothing we can suggest additionally.

Regards,

**Comment by tSlash99** [comment] 2020-11-11 13:57
Same issue, Manjaro 20.1.2. Workaround : Drag & drop a diagram into the app.

**Comment by martinclauss** [comment] 2020-11-11 14:55
Same problem under Fedora 32 and i3 window manager.

**Comment by comxd** [comment] 2021-02-20 12:27
I have fixed this issue on a Kubuntu 20 using fc-cache:

```
sudo rm /var/cache/fontconfig/*
rm ~/.cache/fontconfig/*
fc-cache -r
```

**Comment by martinclauss** [comment] 2021-02-22 09:53
I recently upgraded to Fedora 33. The problem still persists. Suggestions from @comxd unfortunately didn't work.

**Comment by SirStephanikus** [comment] 2021-03-08 13:17
Same issue on XUbuntu 20.04 LTS and Ubuntu 20.04 LTS

**Comment by Cleeb122** [comment] 2021-04-06 07:29
Hi, I'm experiencing the same issue on Manjaro. I understand Manjaro isn't supported, but I was wondering if there are any potential dependency fonts that might be missing. If so a fix may be to install the (potentially) missing fonts. Is there any information that may help?

**Comment by kenalexandersson** [comment] 2021-11-30 07:17
I have the same problem on Fedora 35. Considering the creation date of this issue, am I to believe that that this issue is not prioritized, or no workaround will be presented?

**Comment by davidjgraph** [comment] 2021-11-30 11:28
Duplicate of #368

**Closed by davidjgraph** 2021-11-30 11:28 UTC

**Comment by anescdev** [comment] 2022-11-03 10:18
> I have fixed this issue on a Kubuntu 20 using fc-cache:
> 
> ```
> sudo rm /var/cache/fontconfig/*
> rm ~/.cache/fontconfig/*
> fc-cache -r
> ```

Working on Ubuntu 22.04

**Comment by Mehrab-Farhadzadeh** [comment] 2023-07-30 12:38
> 

Worked on Ubuntu 20.04

**Comment by Mehrab-Farhadzadeh** [comment] 2023-07-30 12:39
> I have fixed this issue on a Kubuntu 20 using fc-cache:
> 
> ```
> sudo rm /var/cache/fontconfig/*
> rm ~/.cache/fontconfig/*
> fc-cache -r
> ```

Worked on Ubuntu 20.04

**Comment by ltsali8220** [comment] 2025-02-19 18:39
hey thanks it'w working on Kali Linux 24.04

**Comment by dabartmess** [comment] 2025-04-26 16:24
> > I have fixed this issue on a Kubuntu 20 using fc-cache:
> > ```
> > sudo rm /var/cache/fontconfig/*
> > rm ~/.cache/fontconfig/*
> > fc-cache -r
> > ```
> 
> Working on Ubuntu 22.04

DOES NOT WORK...
