### ISSUE TITLE
Dialog windows show cryptic characters

### ISSUE THREAD

**Issue by baermathias** [jgraph/drawio-desktop#536] opened 2021-03-29 07:32 UTC
**Describe the bug**
When trying to save a project, the dialog windows show me the following:

![Screenshot from 2021-03-26 19-04-01](https://user-images.githubusercontent.com/45003352/112801506-42b82280-9071-11eb-818e-32ab8d7c45b6.png)
![Screenshot from 2021-03-26 19-03-43](https://user-images.githubusercontent.com/45003352/112801510-43e94f80-9071-11eb-83b9-2be6b72157de.png)

**To Reproduce**
1. Install on Ubuntu 20.04
2. Start new project and try to `save` it.

**Expected behavior**
Display alphanumerical characters

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 14.5.1

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Additional context**
I am using Ubuntu 20.04 and used a snap to install this.

**Comment by webracer999** [comment] 2021-03-30 17:36
Same problem here under Kubuntu 20.10 with snap-version of drawio (v. 14.5.1)

**Comment by davidjgraph** [comment] 2021-03-31 13:34
Duplicate of #368 

The problem is specific to the snap package.

**Closed as completed by davidjgraph** 2021-03-31 13:34 UTC
