### ISSUE TITLE
Zoom problem

### ISSUE THREAD

**Issue by kenixFog** [jgraph/drawio-desktop#850] opened 2021-12-24 02:28 UTC
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Zooming in and out is not smooth. 

**To Reproduce**
Press ctrl and slide the mouse wheel: 5%---10%---15%--20%--70%--245%

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 16.0.2

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by mararad** [comment] 2021-12-24 08:33
Hi,

When you say smooth, what does it mean? What is the problem exactly, please?

Thanks,

**Comment by luwanjia** [comment] 2021-12-29 09:00
Same problem, version 16.0.2 for windows, when slide the mouse one step, it zoom in from 100% to 165%，it looks too large. 125% is ok.
![image](https://user-images.githubusercontent.com/23115071/147644505-2c0c9da9-3049-45a9-b8a7-a28ab69add46.png)

**Comment by mararad** [comment] 2021-12-29 09:56
I am not able to reproduce your numbers but I use Win 10 Pro.

drawio 16.0.2 and Ctrl/Alt+mouse wheel
It goes: 100%, 120%, 145%, 175% etc.

Is it possible to attach a video, please?

**Comment by kenixFog** [comment] 2021-12-29 14:32
![h](https://user-images.githubusercontent.com/29566225/147672680-1512ecb8-f96c-4d90-8d5e-4c885cce139c.gif)

**Comment by TPLeung** [comment] 2021-12-30 09:49
Same problem with drawio 16.0.2 on Windows 10 Pro 19044.1415.

**Comment by davidjgraph** [comment] 2022-01-09 09:53
Duplicate of issue in main repo https://github.com/jgraph/drawio/issues/2528

**Closed as completed by davidjgraph** 2022-01-09 09:53 UTC
Labels: blocked/need-repro
