### ISSUE TITLE
Copy As Image for Selection

### ISSUE THREAD

**Issue by pglezen** [jgraph/drawio-desktop#560] opened 2021-04-27 20:02 UTC
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When a select a portion of my image, **Edit → Copy as Image** should only copy the selection, not the entire image.

See note below about versions.

**To Reproduce**
1. Create two small boxes.
2. Select one.
3. Select **Edit → Copy as Image**.
4. Pasting somewhere else results in both boxes.

**Expected behavior**
I expected **Copy as Image** to only copy the selection.  I think it worked like this in the past.  But maybe I'm just loosing it.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version: `14.5.1` on macOS
- This works as expected using online version `14.6.6`.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7

**Additional context**
This feature works fine using the online version at `14.6.6`.  But when I try to download a newer one, the link goes to `14.5.1`.

**Comment by davidjgraph** [comment] 2021-04-27 20:48
Duplicate of #535

**Closed as completed by davidjgraph** 2021-04-27 20:48 UTC

**Comment by pglezen** [comment] 2021-04-27 20:54
I'm sorry.  I should not have restricted my issue search to open issues.  Thanks for the attention.
