### ISSUE TITLE
The characters in shapes blur when editting

### ISSUE THREAD

**Issue by NewtMa** [jgraph/drawio-desktop#402] opened 2020-10-14 07:51 UTC
This just makes my eyes hurt

**Comment by NewtMa** [comment] 2020-10-14 07:52
I'm using AppImage on Ubuntu 20.04

**Comment by davidjgraph** [comment] 2020-10-14 07:56
Duplicate of https://github.com/jgraph/drawio-desktop/issues/387

**Closed by davidjgraph** 2020-10-14 07:56 UTC
