### ISSUE TITLE
When exporting PDF with grid, backgrounds are ignored.

### ISSUE THREAD

**Issue by ZRQZRQZRQ** [jgraph/drawio-desktop#871] opened 2022-01-15 02:36 UTC
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
When grid is exported to a PDF, background colors are always ignored.

**To Reproduce**
1. Set a background color
2. Export PDF with Grid
3. **Open it......Oops, background color is missing.**

**Expected behavior**
Background and grid can be all exported when applied.

**Screenshots**
![image](https://user-images.githubusercontent.com/39260418/149605697-2fb83f5e-76d9-4a2f-bba5-32cdd7ad908a.png)
![image](https://user-images.githubusercontent.com/39260418/149605786-59d57e49-7232-4e0f-a2f2-869bc914b9e3.png)
![image](https://user-images.githubusercontent.com/39260418/149605810-3e37769c-1787-44cd-9699-6636e315b301.png)
# bug！
**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 16.1.2

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**

**Comment by davidjgraph** [comment] 2022-01-15 10:14
Duplicate of #713

**Closed as completed by davidjgraph** 2022-01-15 10:14 UTC
