### ISSUE TITLE
Recently had a memory issue in the desktop app.

### ISSUE THREAD

**Issue by sxt9** [jgraph/drawio-desktop#462] opened 2021-01-11 15:31 UTC
Recently had this in the desktop app. 
Screenshot below: 
![Draw io_MemoryUse](https://user-images.githubusercontent.com/17098837/103468610-f2a71980-4d28-11eb-983c-422dfea7dcf3.png)

I didn't have any diagrams open. I was not attending my computer for a few hours and came back to this.

_Originally posted by @sxt9 in https://github.com/jgraph/drawio/issues/87#issuecomment-753543665_

**Comment by davidjgraph** [comment] 2021-01-11 15:35
Duplicate of #431

**Closed by davidjgraph** 2021-01-11 15:35 UTC
