### ISSUE TITLE
Improvement when editing a text.

### ISSUE THREAD

**Issue by taozina0587** [jgraph/drawio-desktop#818] opened 2021-12-03 10:59 UTC
When placing text on a diagram, I cannot edit just one word. If I make it bold, put a color difference or any other change to just one word, the entire text will be affected.

**Comment by mararad** [comment] 2021-12-06 12:24
Which version and OS are you using? Can you attach video showing all the steps and the result, please?
I tested in Win 10 Pro with drawio 15.8.7 and couldn't reproduce the issue.

![issue](https://user-images.githubusercontent.com/44292306/144845548-2fda59f9-35b9-4f4c-a475-a3ae201ba91b.JPG)

**Comment by taozina0587** [comment] 2021-12-06 13:20
At the time I wrote this problem, I was using windows 11 on version 15.8.7. I went back to windows 10 due to windows 11 having problems with my work. I tested this defect again and it resolved. So I believe that the program on windows 11 has this problem.

**Comment by davidjgraph** [comment] 2021-12-07 14:18
Closing due to inability to reproduce.

**Closed as completed by davidjgraph** 2021-12-07 14:18 UTC
