### ISSUE TITLE
Opening files redirect to welcome screen

### ISSUE THREAD

**Issue by belkacem-co** [jgraph/drawio-desktop#840] opened 2021-12-20 09:47 UTC
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Description**
After updating to v16.0.0, when opening a *.drawio file, the content is displayed and the application quickly redirects you to the welcome page (the one you create a new diagram or open a new file from)

**To Reproduce**
1. Close the application if it is opened
2. Open an existing file (directly by double clicking on the file)

**Expected behavior**
The file should be opened directly

**draw.io version :**

- draw.io version 16.0.0

**Desktop:**
 - OS: MacOS Monterey 12.1

**Workaround**
1. In the welcome page, choose 'Open existing diagram'
2. Choose the file

**Comment by davidjgraph** [comment] 2021-12-20 09:51
Duplicate of #838

**Closed as completed by davidjgraph** 2021-12-20 09:51 UTC
