### ISSUE TITLE
According to the custom horizontal or vertical spacing size, realize equal spacing horizontal distribution or vertical distribution

### ISSUE THREAD

**Issue by luomgf** [jgraph/drawio-desktop#1454] opened 2023-09-09 10:03 UTC
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
When I need to typeset multiple shapes and assign them to a specified spacing value, such as 0 or other numerical values, I cannot complete this operation. Neither horizontal nor vertical specified spacing operations can be completed.

**Describe the solution you'd like**
By adding an input box for entering a specified value next to the existing spacing distribution button, you can achieve specified spacing distribution in the horizontal or vertical direction.

**Describe alternatives you've considered**
I want to express such a function
![image](https://github.com/jgraph/drawio/assets/18029400/ae63c2f4-4299-43dc-920a-d0782e8ebc21)
Now the positions of A1 and B1 are not equal, but I want to set them to the specified size distance

Then I input 20pt at the position of C, and click the d horizontal distribution button

The distance between them becomes A1 and B1, which becomes a custom 20pt

**Additional context**
The main background of this requirement is that when we need to accurately layout graphic spacing, we need the support of this feature.

Thanks for the reply Thanks！

**Comment by davidjgraph** [comment] 2023-09-13 12:09
Duplicate of https://github.com/jgraph/drawio/issues/3842

**Closed as completed by davidjgraph** 2023-09-13 12:09 UTC
