### ISSUE TITLE
Remove link "draw.io" in the menu

### ISSUE THREAD

**Issue by tvset** [jgraph/drawio-desktop#533] opened 2021-03-21 09:33 UTC
Hello,
Please move the link "draw.io" which is located above the menu. And then it takes up the whole field.
thank. 
![draw](https://user-images.githubusercontent.com/17748653/111900107-99a27400-8a41-11eb-8c0b-f9ec65a538a9.PNG)

**Comment by davidjgraph** [comment] 2021-03-21 16:33
Duplicate of #91

**Closed by davidjgraph** 2021-03-21 16:33 UTC
