### ISSUE TITLE
EINVAL: invalid argument, write

### ISSUE THREAD

**Issue by wirwolf** [jgraph/drawio-desktop#942] opened 2022-03-24 08:42 UTC
**Describe the bug**
Save file to PC damage  file and display error

**To Reproduce**
1. Create a new diagram
2. Try to save the diagram
3. See error

**Expected behavior**
File saved

**Screenshots**
![image](https://user-images.githubusercontent.com/8457572/159876372-ea9177ff-7f3b-4190-94aa-24ac52ce5a80.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 17.1.5

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: instaling from snap
 - Version 17.1.5

**Comment by hasnimehdi91** [comment] 2022-03-24 10:35
I am facing the same issue.

**Comment by davidjgraph** [comment] 2022-03-24 11:42
Duplicate of #941

**Closed as completed by davidjgraph** 2022-03-24 11:42 UTC
