### ISSUE TITLE
Placeholders help popup cannot be closed.

### ISSUE THREAD

**Issue by bt-tech-dd** [jgraph/drawio-desktop#816] opened 2021-12-02 20:47 UTC
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The information window for the placeholders that pops up after clicking the question mark does not have a way to close it.

**To Reproduce**
1. Drag any shape from the shape list to the drawing area to create a shape.
2. Right click on the shape
3. Click Edit Data...
4. Click the question mark next to Placeholders
5. The placeholders information popup appears with no way to close it

**Expected behavior**
Expectation is to have a way to close the window.

**Screenshots**
Dragged shape to drawing area
![image](https://user-images.githubusercontent.com/68382967/144499725-d24bb15f-1228-430e-a568-664a2706b50a.png)

Right click the shape and click Edit Data...
![image](https://user-images.githubusercontent.com/68382967/144499914-65fcd477-b96b-477d-8906-bca75be9c9b7.png)

Click the question mark
![image](https://user-images.githubusercontent.com/68382967/144500006-72fc7d2e-21ce-480f-a30f-6d6fde467a07.png)

The popup appears with no way to close it
![image](https://user-images.githubusercontent.com/68382967/144500176-d425433a-bd7a-41ad-b04a-34195e8a9539.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 15.8.7

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**

**Comment by mararad** [comment] 2021-12-06 11:48
Hi, 

I couldn't reproduce this. Could you uninstall/re-install the app and tell me if it helps?

https://user-images.githubusercontent.com/44292306/144840858-1c257bc4-36ad-4418-8d89-aeab2fab3aa2.mp4

**Comment by bt-tech-dd** [comment] 2021-12-06 13:08
Clicking away from the popup does not close it. The popup just gets put behind the main window. Uninstalling and reinstalling does not change the behavior.

Clicking away from the popup and clicking the ? button again produces multiple popups.

**Comment by mararad** [comment] 2021-12-06 13:27
You are right. Reproduced on Win 10 Pro and drawio 15.8.7

**Comment by davidjgraph** [comment] 2021-12-21 23:05
Fixed in 16.0.0

**Closed as completed by davidjgraph** 2021-12-21 23:05 UTC
