### ISSUE TITLE
Not working on linux

### ISSUE THREAD

**Issue by mayanksuman** [jgraph/drawio-desktop#158] opened 2019-09-09 10:07 UTC
Draw.io v11.2.4 fail on linux. I have tested both AppImage and `.deb` version. Both fail with following error.
`[19217:0909/153930.193173:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/draw.io/chrome-sandbox is owned by root and has mode 4755.
`

There is no way AppImage can be used but deb version after installation works if following two commands are issued.
```
sudo chown root /opt/draw.io/chrome-sandbox
sudo chmod 4755 /opt/draw.io/chrome-sandbox
```

I think this can be easily implemented in `deb` version so that user can directly use program after installing.

**Comment by davidjgraph** [comment] 2019-09-09 10:11
Duplicate of https://github.com/jgraph/drawio-desktop/issues/150 ?

**Comment by mayanksuman** [comment] 2019-10-10 07:01
Yes, it is a duplicate. The deb installer also has same problem as rpm.

**Closed** 2019-10-10 09:07 UTC
