### ISSUE TITLE
Text tabs/indentation gets deleted on ctrl+v

### ISSUE THREAD

**Issue by Fvvp** [jgraph/drawio-desktop#898] opened 2022-02-01 17:47 UTC
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
All text indentation is removed from a block after pressing "ctrl+V". 

(Interestingly though, if you press tab "while in the middle of text" [like  "aaaaa     bbbbb"] then  ctrl+V, all indentation gets replaced by a single space ["aaaaa bbbbb"])

**To Reproduce**
1. create a new block (ie square)
2. double click it to insert text in it
3. press "tab" then type anything
4. press "enter" then type some more text
5. press "ctrl+v"

**Expected behavior**
indentation should be unnaffected

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 16.5.1

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
I dont know if the following is a separate bug but if you ctrl+v text copied FROM the textbox itself, the pasted text will break the line after it

**Comment by tanghoiy** [comment] 2023-03-10 19:22
I can confirm that this is still an issue and highly repeatable. The pasting of anything while editing text removes all tab indentation in the existing text

**Comment by ncc-74205** [comment] 2023-10-13 09:05
I can confirm this, too. This issue should be fixed since it is a serious productivity killer if tabs are used in textboxes.

**Comment by voloddia** [comment] 2024-01-29 12:07
For me, all indentations are automatically turn into 4 spaces whenever pasting, which messes up everything in that textbox. 
This is reproducible in both desktop and web apps.

**Closed as not planned** 2024-10-20 03:47 UTC
Labels: declined
