### ISSUE TITLE
API for csv import 

### ISSUE THREAD

**Issue by daknhh** [jgraph/drawio-desktop#807] opened 2021-05-10 07:15 UTC
It would be perfekt if diagrams.net /draw.io could offer an API for csv / sql import which returns an png or draw.io as response - right now its just possible to do it via browser.

**Comment by souliane** [comment] 2021-12-27 14:44
I also think that this is a great feature to add.

I am writing a converter that outputs CSV for diagrams.net, and this would save me dozens of copy/clicks/paste/clicks.

**Comment by davidjgraph** [comment] 2021-12-29 14:28
Duplicate of #202

**Closed as not planned by davidjgraph** 2021-12-29 14:28 UTC
Labels: declined
