### ISSUE TITLE
UI is almost unreadable on 4k display

### ISSUE THREAD

**Issue by jbulow** [jgraph/drawio-desktop#949] opened 2022-04-06 08:00 UTC
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The UI is unreadable on 4K display. No option to zoom UI.

**To Reproduce**
1.start draw.io desktop app

**Expected behavior**
Usable UI

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 17.2.4

**Desktop (please complete the following information):**
 - OS: Ubuntu

**Additional context**

**Comment by jbulow** [comment] 2022-04-06 19:11
As a workaround I start drawio from command line with flag `--force-device-scale-factor=2`.

Would be nice to have something similar to ctrl-+ and ctrl-- that works in the web based version.

**Comment by vmsh0** [comment] 2022-08-03 08:48
This was marked as completed, but does this mean an actual solution has been introduced or that the workaround should be used?

**Comment by MaxVRAM** [comment] 2022-08-18 07:02
This is especially a problem with the shape library. It's a shame to spend time hovering over several shapes with small differences to pick the right one when there's so much free desktop space.

**Comment by davidjgraph** [comment] 2022-08-18 08:26
I cannot recreate the issue. I have both 4k and 5k displays and don't get these issues. Someone needs to file a reproducible report.

**Comment by dmarrazzo** [comment] 2024-02-21 09:14
How do you zoom the UI? e.g. the menu font size?

**Comment by geekq** [comment] 2024-02-21 09:25
> How do you zoom the UI? e.g. the menu font size?

In the online-version using web browser's Ctrl-+ makes both bigger, the diagram content and the UI elements.
In the desktop version, only diagram content becomes bigger. I am using the workaround mentioned above: `--force-device-scale-factor=2` switch on application start.

**Comment by dmarrazzo** [comment] 2024-02-21 09:43
I'm interested in the desktop version on Wayland Linux (flatpack) and unfortunately the workaround does not work (actually it has a strange effect that make the UI unusable).

**Comment by davidjgraph** [comment] 2024-05-01 12:21
Closing due to lack of repro.

**Closed as not planned by davidjgraph** 2024-05-01 12:21 UTC
