### ISSUE TITLE
Background image missing when exporting to PDF

### ISSUE THREAD

**Issue by kewalaka** [jgraph/drawio-desktop#1044] opened 2022-06-14 01:19 UTC
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

If you use another page as a background, and export to PDF, the background is missing from the exported PDF document.

**To Reproduce**

1. Create a background page
2. Create a foreground page, 
3. On the foreground page select the Diagram tab -> tick Background, select change, select the "background page" as the background image
4. Export the diagram to a PDF.  
5. The background is missing.

**Expected behavior**

Background is displayed, as it is when exporting to other formats and as visible in the UI.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

draw.io desktop client - 19.0.3

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser n/a
 - Version 11

**Additional context**

**Comment by davidjgraph** [comment] 2022-06-14 08:08
Duplicate of #713

**Closed as completed by davidjgraph** 2022-06-14 08:08 UTC
