### ISSUE TITLE
"Copy as Image" desktop command does not respect selection

### ISSUE THREAD

**Issue by mkestes42** [jgraph/drawio-desktop#559] opened 2021-04-27 16:22 UTC
With the draw.io desktop application (14.5.1), the "Copy as Image" creates an image of the entire canvas and not the selected objects.

I'm fairly certain this was a recent change.  I recently switched to draw.io desktop and love it, and I am fairly sure that this worked when I first started using it a few months ago.

Steps to recreate:
1) Create 2 objects in a new document.
2) "Copy as Image" with 1 object selected.
3) Paste anywhere and see an image with 2 objects.

**Comment by alderg** [comment] 2021-04-27 17:28
Duplicate of #535

**Closed as completed by alderg** 2021-04-27 17:28 UTC
