### ISSUE TITLE
Not saving New Diagrams 

### ISSUE THREAD

**Issue by Hygens** [jgraph/drawio-desktop#715] opened 2021-09-24 12:56 UTC
I have problems on manjaro linux because after create one diagram and attempt save not saving nothing.
1. Go to Create New Diagram -> Cloud -> AWS
2. Click on Save or Save as...nothing saved on Manjaro Linux:
![Screenshot from 2021-09-24 09-53-59](https://user-images.githubusercontent.com/5247983/134677468-fe86a46c-10e6-440c-9976-6b1c722817ee.png)

**Expected behavior**
Save diagram via Save or Save as...

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io desktop version 15.2.7

**Desktop (please complete the following information):**
 - OS: Manjaro Linux

**Comment by nitomartinez** [comment] 2021-09-26 07:16
Happening also with:

**draw.io version (In the Help->About menu of the draw.io editor):**

* draw.io desktop version 15.2.7

**Desktop (please complete the following information): **

* OS: Ubuntu 20.4 with Mate Desktop

Error on the command line:

```
[10635:0926/091826.581458:ERROR:browser_main_loop.cc(269)] Gtk: gtk_native_dialog_run: assertion '!priv->visible' failed
```

Probably duplicate of #706

**Comment by kantorv** [comment] 2021-09-28 00:09
Same here (ubuntu 20.04). Anyway found that it's possible to select and copy desktop drawings and paste to online app.. 
`[1617722:0928/030041.375871:ERROR:browser_main_loop.cc(269)] Gtk: gtk_native_dialog_run: assertion '!priv->visible' failed`

**Comment by davidjgraph** [comment] 2021-09-28 16:51
I'm going to assume this is the same underlying issue as https://github.com/jgraph/drawio-desktop/issues/706

**Closed as completed by davidjgraph** 2021-09-28 16:51 UTC
