### ISSUE TITLE
21.6.1 Broke diagram background page

### ISSUE THREAD

**Issue by ckambiselis** [jgraph/drawio-desktop#1375] opened 2023-07-07 08:51 UTC
After updating to the latest version, the background page setting is acting weird, texts are not shown at all and images are color inverted.

First noticed on a file I was editing and decided to update before continuing, and when it opened again the background texts where missing.

Made a new file and the problem still exists, attached are screenshots of the settings used, the normal page and the background page.

<img width="1285" alt="Settings" src="https://github.com/jgraph/drawio-desktop/assets/31256300/adbbc567-6c9e-4779-96c0-fa81b3ef0f61">
<img width="1285" alt="Normal page" src="https://github.com/jgraph/drawio-desktop/assets/31256300/8763e741-cd3b-491a-bfaf-daed83d1ebe4">
<img width="1285" alt="Background page" src="https://github.com/jgraph/drawio-desktop/assets/31256300/791b4654-c60b-4ac9-b52c-805f3b2b27d7">

**Comment by mararad** [comment] 2023-07-07 12:35
The issue is reproduced. Diagram page (using the background page as image) shows inverted image colors/or image missing and text color to almost invisible (light gray). At my place text remains but you can hardly see it.

Also drawio logo is almost transparent. 

* In diagrams.net online 21.6.1 in the latest Chrome and FF the image has inverted colors and almost invisible text

![online](https://github.com/jgraph/drawio-desktop/assets/44292306/d223a1e5-e329-4486-ba83-5e6f08548623)

* In the desktop app 21.6.1 (Win 10) image is completely missing and text is almost invisible

![background page](https://github.com/jgraph/drawio-desktop/assets/44292306/a3204542-304a-465d-9309-1b5aec8e6847)
![page 2](https://github.com/jgraph/drawio-desktop/assets/44292306/a0b3638b-15ab-4e47-8a78-d49d948fc095)

**Comment by mararad** [comment] 2023-07-07 12:44
Got the feedback from our engineers. The issue is fixed internally and it will be in the next release

**Comment by davidjgraph** [comment] 2023-07-11 15:45
Fix in 21.6.2

**Closed as completed by davidjgraph** 2023-07-11 15:45 UTC
