### ISSUE TITLE
Smooth zooming?

### ISSUE THREAD

**Issue by SanjayVyas** [jgraph/drawio-desktop#278] opened 2020-05-03 08:15 UTC
I am using a mac with draw.io desktop and haven't figured out how to zoom smoothly.

The CMD Plus, CMD Minus keys don't seem to work in my mac (maybe it's clashing with some other mac short cut)

Pinch zoom is toooo rapid, it suddenly zooms from 50% to 400% with the slightest of a pinch.
Same with CMD touchpad scroll.. too rapid zooming.

That leaves the zoom drop-down and zoom in and zoom buttons, which have to be done by moving the mouse between presentation, which is distracting. Also, I want to zoom at the current mouse position and not general zoom.

How do I do, smooth slow zoom at the current mouse position in draw.io desktop? Any help is appreciated.

**Comment by SanjayVyas** [comment] 2020-05-13 19:24
Any help with this? If not smooth zooming (1 pt instead of 10 points at a time), at least have a key combo work on Mac? Mac doesn't have numeric keypad so can't do CTRL and NumPad + or 
Currently, during a live session, I have to move the mouse to zoom in/zoom out button to change the zoom.

**Comment by davidjgraph** [comment] 2020-05-16 09:26
Duplicate of https://github.com/jgraph/drawio-desktop/issues/52

**Closed by davidjgraph** 2020-05-16 09:26 UTC
