### ISSUE TITLE
Draw IO update is failing

### ISSUE THREAD

**Issue by surapuramakhil** [jgraph/drawio-desktop#282] opened 2020-05-06 12:35 UTC
I am running draw io version around 12 I guess. it shows for update and press of update screen gets this message. It says file not found app-update.yml

I have installed it from .deb file

![Screenshot from 2020-05-06 18-03-10](https://user-images.githubusercontent.com/9161543/81177342-1bbdb180-8fc4-11ea-8155-d0c418036602.png)

**Comment by davidjgraph** [comment] 2020-05-16 09:23
Duplicate of https://github.com/jgraph/drawio-desktop/issues/138

**Closed by davidjgraph** 2020-05-16 09:23 UTC
