### ISSUE TITLE
Adding shapes to custom library gives an error

### ISSUE THREAD

**Issue by SanjayVyas** [jgraph/drawio-desktop#265] opened 2020-04-23 08:01 UTC
I had posted this issue earlier but somehow I cannot locate it any longer... maybe it has been cleared from the issue list

I have been facing this issue in the previous Desktop version and it persists in 13.0.1 version as well

**Issue**: Trying to add a shape to a custom library results in an error "this.getFilename is not a function".

**Steps to reproduce**
1. Open a new file [File>New]
2. Create a new library [File>New Library]
3. Create a shape [Drag a rectangle] and select it
4. Click on the "+" in the custom library to add the shape
5. Save the file [File > Save > Temp.drawio]
6. Exit draw.io desktop
7. Run draw.io desktop
8. Open the drawing [File > Open > Temp.drawio]
9. Create a shape [Drag a circle] and select it
10. Click on "+" of the Library again
This results in an exception now
![image](https://user-images.githubusercontent.com/1856233/80074382-adf69c00-8566-11ea-8f6e-760759cf19c6.png)

**Environment**
macOS 10.15.4
draw.io desktop 13.0.1

**Comment by davidjgraph** [comment] 2020-04-23 08:23
https://github.com/jgraph/drawio/issues/861

**Comment by SanjayVyas** [comment] 2020-04-23 08:54
Sorry for multiple post...
One, I had earlier posted it in draw.io, whereas this is specific for Desktop version.
Second, I was hoping this would have been fixed in the new release 13.0.1

Funnily, I searched for the earlier post and could not find it.. maybe I need to up my skills on searching issues on Github. 

Apologies.

**Comment by davidjgraph** [comment] 2020-04-29 11:47
Duplicate of https://github.com/jgraph/drawio-desktop/issues/274

**Closed by davidjgraph** 2020-04-29 11:47 UTC
