### ISSUE TITLE
White screen when opening from file on Windows 11

### ISSUE THREAD

**Issue by TechGeek01** [jgraph/drawio-desktop#854] opened 2021-12-28 01:54 UTC
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
When opening from a .drawio file as an existing diagram, the "open" screen goes away, but the diagram never loads, leading to a white screen, as shown below.

This seems to happen after an update to 16.0.2, both with an in place upgrade, and a full uninstall and reinstall.

**To Reproduce**
1. Open the application, and click "open existing diagram"
2. Browse to the diagram file, and load

**Expected behavior**
The diagram should load into the program, and content should be displayed, rather than a hanging white screen with no ability to close the window aside from task manager.

**Screenshots**
![image](https://user-images.githubusercontent.com/3240812/147518888-ebcf7401-8e8e-417c-a894-88a4b3b3dcc9.png)

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 16.0.2

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro build 22000.376 x64

**Additional context**
Loading this diagram file in the website works perfectly fine. I can confirm it's not something corrupt or weird in my diagram file.

**Comment by mararad** [comment] 2021-12-28 08:35
I tested at my place and all is working fine but I am Win 10 Pro user so might be related to Win 11 you are using
(drawio 16.0.2)

You mentioned it's not related to the diagram but if possible attach the file so it can be tested.

Regards,

**Comment by davidjgraph** [comment] 2021-12-28 18:57
Duplicate of #853

**Closed as completed by davidjgraph** 2021-12-28 18:57 UTC
