### ISSUE TITLE
Plugins don't work in 13.0.1 desktop version

### ISSUE THREAD

**Issue by kadimgh** [jgraph/drawio-desktop#276] opened 2020-05-01 00:09 UTC
I've tried couple of plugins (svgdata, sql, others...) and none of them seem to work in the desktop version, while they do work in the web version.

For example sql plugin is supposed to add a menu item under Arrange->Insert menu.

Steps to reproduce:
1. Add the plugin by url to the desktop client https://www.draw.io/plugins/sql.js
2. Relaunch the client, there is a warning about the plugin, press OK: 
![image](https://user-images.githubusercontent.com/7655219/80770082-0ea44c80-8b04-11ea-9778-dd1d3942a519.png)
3. Go to Arrange->Insert, but there is no plugin-related menu items: 
![image](https://user-images.githubusercontent.com/7655219/80770348-e9640e00-8b04-11ea-8a26-bd9ec4653920.png) while there is one in the web version: 
![image](https://user-images.githubusercontent.com/7655219/80770390-0b5d9080-8b05-11ea-9f3a-65466f48fd9e.png)

The issue is the same for svgdata plugin, but it takes more steps to reproduce

**Comment by davidjgraph** [comment] 2020-05-01 07:08
What version of the desktop build are you using?

**Comment by kadimgh** [comment] 2020-05-01 14:36
Originally it was 13.0.1. I've updated to 13.0.3 (the latest) and it has the same issue

**Comment by McFoggy** [comment] 2020-05-13 07:36
+1 I have the same issue on 13.0.3 also.

I didn't find anything related to this plugin loading in the logs under `%USERPROFILE%\AppData\Roaming\draw.io` or subdirectories. Can we change the log level and activate more tracing to help identifying the issue?

**Comment by davidjgraph** [comment] 2020-05-27 21:12
We're not going to add support for remote plugins, for security reasons, but will allow third-party plugins to be added locally. Closing as wontdo / duplicate of https://github.com/jgraph/drawio-desktop/issues/139

**Closed by davidjgraph** 2020-05-27 21:12 UTC

**Comment by kadimgh** [comment] 2020-05-27 21:58
just for the record regarding remote vs. local: the same plugin works fine if loaded locally using file:// url, which is perfectly fine, I just did not know there is a difference in how plugins were treated.

**Comment by McFoggy** [comment] 2020-05-28 06:35
@davidjgraph wouldn't it be possible to add by configuration _'trusted'_ locations ?
In our company we'd like to promote the tool and to provide a company wide plugin. 
But if everyone has to copy locally a version X of the plugin then the delivery method is not viable anymore.
By delivering the plugin via an URL, we also benefit from automatic update.
In order to secure the whole thing would it be enough to have some setup where users could add safe base url like `https://my-company.org/drawio` and then it could be possible to load plugins from `https://my-company.org/drawio/plugins/p1.js`.
Is it viable ?
