### ISSUE TITLE
shape not filled can not be selected in sketch scheme

### ISSUE THREAD

**Issue by casolarcn** [jgraph/drawio-desktop#760] opened 2021-11-06 05:17 UTC
### Preflight Checklist

* [ X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
shape which is not filled ,can not be selected in sketch scheme
**To Reproduce**
1.change to sketch scheme
2.create a new diagram
3.create a new shape,such as as rectangle
4.uncheck "fill" property on style tab of formate page
5.click on the rectangle

**Expected behavior**
the rectangle can be selected

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**
15.4.0
- draw.io version [e.g. 12.6.7]

**Desktop (please complete the following information):**
Windows 10
**Additional context**

**Comment by mararad** [comment] 2021-11-08 12:07
Hi,

Thanks for contacting us but it’s a feature asked by users, not a bug. 

Regards,

**Comment by casolarcn** [comment] 2021-11-09 00:37
thanks.
but,is it expected that unfilled-shape can no be selected?
this does not happen in all other schemes.such as default or dark ,shapes can be selected and move.

**Comment by davidjgraph** [comment] 2021-11-09 10:35
Most whiteboarding style tools behave in this way, diagramming tools behave more along the existing diagrams.net selection. The problem we have is we don't yet know whether users are coming from diagrams.net or other whiteboarding tools.

With the behaviour the other way around we get just as many complaints that we don't align with other similar tools, so whichever option we pick, half of you will not be happy.

**Comment by alderg** [comment] 2021-11-09 12:40
This will be fixed in the next release.

**Closed as completed by alderg** 2021-11-09 12:40 UTC
