### ISSUE TITLE
Create drawio application in the registry

### ISSUE THREAD

**Issue by VirtualEvan** [jgraph/drawio-desktop#84] opened 2019-01-28 16:11 UTC
Can you please add drawio application to the registry?
By creating a file association to drawio the following registry is created
´´´
[HKEY_CLASSES_ROOT\Applications\draw.io.exe\shell\open\command]
@="\"C:\\Program Files\\draw.io\\draw.io.exe\" \"%1\""
´´´
This will allow drawio to be selected when an unknown filetype is opened, and will also help with deployment

![image](https://user-images.githubusercontent.com/12986551/51849260-9c045a00-231f-11e9-9f85-cbbf8d6920b1.png)

**Comment by davidjgraph** [comment] 2019-01-28 16:19
Looks like a duplicate of https://github.com/jgraph/drawio-desktop/issues/35

**Closed by davidjgraph** 2019-01-28 16:19 UTC

**Comment by VirtualEvan** [comment] 2019-01-29 09:10
I understand that you want to keep drawio working with contentypes, but without modifying drawio itself,
isn't possible to do this via installer?

Note that right now the user can do this by itself, but he has to manually search for the .exe

**Comment by davidjgraph** [comment] 2019-01-29 09:10
It probably is possible, just need someone to implment it...

**Comment by wobbol** [comment] 2019-02-13 01:39
master 4e0b7eb8 ← registry 886c9b03
```bash
git checkout -qf %APPVEYOR_REPO_COMMIT%
fatal: reference is not a tree: 4e0b7eb8ad614b799103438d98dadc71d89fa6dd
Command exited with code 128
```
the appveyor run failed, because git couldn't find the commit from master that you referenced. From a little poking around, this seems to be an issue with the build system more than the changes you submitted.
other people talking about appveyor doing this:
 - https://github.com/servo/servo/issues/10251
 - https://help.appveyor.com/discussions/problems/1272-fatal-reference-is-not-a-tree-sha-on-git-checkout

the user in the last link solved this by removing `--depth=1` from 
`git clone --depth=1 -q --branch=%APPVEYOR_REPO_BRANCH%` in their appveyor config.

**Comment by VirtualEvan** [comment] 2019-02-13 09:07
Yes, looks like previous pull requests had the same problem
Maybe using separated clone lines for pull request can help without affecting the current build config for master

PS: I removed my appveyor project, now the link in my previous comment is not working anymore, it was just a log of a success compilation in my forked project

**Comment by davidjgraph** [comment] 2019-06-05 16:49
Installer of 10.7.5 should do this for you https://github.com/jgraph/drawio-desktop/releases/tag/v10.7.5
