### ISSUE TITLE
Font Size defaults to 12 pt in Mac OS despite configuration

### ISSUE THREAD

**Issue by sivaswami** [jgraph/drawio-desktop#1564] opened 2023-12-29 08:16 UTC
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
I use the below entry inside Configuration for  my default vertex configuration. I set my fontsize as "15", but the default node is coming with Node size "12 pt".  What is the difference btw "Set Default Style" option and the "defaultVertexStyle" configuration ?
I believe "set default style" is for a particular session and defaultVertexStyle is for persistence of style across multiple sessions. Please confirm ?

**To Reproduce**

1. Go to configuration
2. Add the below entry as part of configuration (only part of configuration is pasted below)

 "defaultVertexStyle": {
    "rounded": "1",
    "arcSize": "50",
    "align": "center",
    "html": "1",
    "fontSize": 15,
    "fontFamily": "Pangolin",
    "fontStyle": 1,
    "fontSource": "https://fonts.googleapis.com/css?family=Pangolin&display=swap",
    "fillColor": "#E8EAF6",
    "fontColor": "#000000",
    "strokeColor": "#0A1172",
    "sketch": "1",
    "curveFitting": "1",
    "jiggle": "2",
    "fillStyle": "solid",
    "strokeWidth": "3",
    "whiteSpace": "wrap"
  }

3. Apply configuration and restart Draw.io
4. Create a new node. 
5. The new vertex style will not match "Configured" vertex style.

**Expected behavior**

The startup vertex style to match entry in the Persisted configuration  rather than  "set default style" option.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version x.y.z
22.1.15

**Desktop (please complete the following information):**
 - OS: Windows, MacOS, Linux...
MacOS

**Additional context**

**Comment by m-mohamedin** [comment] 2024-01-03 21:17
![Screenshot 2024-01-03 at 4 15 22 PM](https://github.com/jgraph/drawio-desktop/assets/24944765/977467c0-df9a-44d1-8f94-07483e6f695d)
Unfortunately, we cannot reproduce. Please send us the full configuration and steps to reproduce

**Comment by sivaswami** [comment] 2024-01-04 16:55
Full configuration: https://gist.github.com/sivaswami/e706a926de8db30fae7a121c323486ec

## Reproducing steps ##
1. I created a new vertex with size 12 font and some colors.
2.  set this shape as default shape (cmd + shift + D)
3. Update the configuration with my configuration (15 pt default size).
4. close the drawio window
5. Open a new instance
6. Create a vertex/node( Press D shortcut). it defaults to 12 font and not 15 font
7. But if I create a new vertex using  copy on connect (drag the connector), it is creating vertex with 15 pt font(works as expected).
Hope this clarifies. Let me know if you need additional details

**Comment by m-mohamedin** [comment] 2024-01-04 20:04
Thanks for the file and detailed steps.

Unfortunately, we still cannot reproduce. Once the instance is closed, the default style is cleared even if the file is saved.

**Comment by sivaswami** [comment] 2024-01-04 20:08
<img width="578" alt="image" src="https://github.com/jgraph/drawio-desktop/assets/1367716/516a3853-53e0-40c1-93ac-a0e120abcd7b">

**Comment by sivaswami** [comment] 2024-01-04 20:09
This is what I see. After starting the draw.io, even if my configuration contained font size as "15pt", I see it defaults to "12"

**Comment by sivaswami** [comment] 2024-01-04 20:17
This issue happens in sketch theme. I tried the same with other theme, works fine.

**Comment by m-mohamedin** [comment] 2024-01-05 13:48
Thanks for the detailed info, we managed to reproduce and the issue will be fixed in the next release
Thanks for the report

**Closed as completed by m-mohamedin** 2024-01-05 13:48 UTC

**Comment by davidjgraph** [comment] 2024-01-09 21:35
In desktop release 22.1.18

**Comment by sivaswami** [comment] 2024-01-11 04:21
Thanks. Verified the fix. working
