### ISSUE TITLE
Try to print landscape mode.  Prints portrait mode instead (Windows)

### ISSUE THREAD

**Issue by jeff922** [jgraph/drawio-desktop#517] opened 2021-02-28 15:48 UTC
* [X ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Printing with Landscape mode selected still prints in Portrait mode.

**To Reproduce**
File -> New -> Network > network.lan.xml

File -> Print.  Fit to 1 sheet across 1 down, Paper Size = US-Letter 8.5x11" Landscape still prints in Portrait mode.  HP Printer.

Changing paper size to/from portrait and landscape in print dialog has not affect on print orientation.  Changing paper size from Diagram tab also does not appear to rotate the printout.

**Expected behavior**
I expect the printed output to be rotated 90 degrees when fitted to one page, so printout takes up full sheet of paper.

- draw.io version
- 14.4.3

**Desktop (please complete the following information):**
Windows 10 20H2 19042.804

**Comment by mararad** [comment] 2021-03-01 10:24
Hi,

if change to Landscape in Preferences section, does it help?
If not, you could try File > Export as > Advanced > PDF and change settings. 

Regards,

**Comment by jeff-at-keysight** [comment] 2021-03-01 13:14
The export Advanced PDF is a good workaround.  That works for now.

I could not find a Preference section in the draw.io GUI.  I this is the Diagram ->Paper Size tab, I tried changing from portrait to landscape there, but I don't see any change

**Comment by maps0n** [comment] 2021-11-01 09:39
Hi,
for the record, in draw.io on 15.4.0  running on macOS 11.6 the problem is still present.
@mararad Thank you for the workaround.
regards Herb

**Comment by dunxd** [comment] 2021-11-19 18:21
See the same in 15.7.3.  In both Macos (Intel) and Windows version of draw.io, the print interface gives Portrait and Landscapes as options.  However, the setting does not seem to be passed through to the OS printing interface - select Landscape, and the printout still arrives in portrait.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to Print
2. Select landscape
3. Click Ok
4. On Mac, click Show details - in the Layout page, Portrait is selected.
On Windows 10, select a printer and click Preferences. Portrait is selected. This is the case for the printer I have and Microsoft Print to PDF

The selection in draw.io is not getting passed through to the OS printing service.

**Comment by twojtyniak** [comment] 2022-12-07 19:03
v20.3.0 on MacOS 12.6.1 still exhibits this problem. Most vexing. Is this on the To Fix list? The wontfix tag is a little disconcerting for such a fundamental problem.

**Comment by wrldtvlr** [comment] 2023-05-04 13:25
The portrait / landscape preference failure still exists in Windows 11 / 21.2.8. Even though I have landscape as my canvas and printing preference in draw.io, I have to change the orientation in my printer dialog.

**Comment by m-mohamedin** [comment] 2023-09-29 19:41
A fix for the portrait/landscape option in the system dialog will be added in the next release

**Comment by davidjgraph** [comment] 2023-10-03 11:34
Fix in 22.0.2.

**Comment by wrldtvlr** [comment] 2023-10-03 13:05
Sorry - upgraded to 22.0.2 and printed a document set to landscape. Still comes out in portrait unless I change the system dialog. Windows 11.

**Comment by m-mohamedin** [comment] 2023-10-03 13:21
> Sorry - upgraded to 22.0.2 and printed a document set to landscape. Still comes out in portrait unless I change the system dialog. Windows 11.

I believe this is a bug in Electron itself, we set the landscape in the settings and it works on macOS but not on Windows

**Comment by fixinproblems** [comment] 2023-12-06 14:54
I am using the 22.1.2 version on Windows 10 Pro.

I am not able to print in landscape mode OR do a print preview.

I tried using the settings on the right under 'Diagram' AND going under 'File > Page Setup' ... neither worked.

Thanks for your work on this, I do love draw.io!

**Comment by Rubber-Duckie** [comment] 2024-01-02 20:27
same here, sadly this project is over even the basics are trash. Back to viso

**Comment by m-mohamedin** [comment] 2024-06-07 23:41
Is this still an issue in the latest release. I've just tried and it looks OK to me
![Screenshot 2024-06-07 at 7 40 22 PM](https://github.com/jgraph/drawio-desktop/assets/24944765/42c6b987-46f0-45e1-942c-1542098a2585)

**Comment by wrldtvlr** [comment] 2024-06-08 16:39
I agree - it appears to be working correctly in build 24.5.1.

**Closed** 2024-06-08 17:52 UTC
