### ISSUE TITLE
Saving and Export Dialog Display Issue

### ISSUE THREAD

**Issue by reya276** [jgraph/drawio-desktop#662] opened 2021-07-27 16:43 UTC
I encountered a display issue on Ubuntu 20.04LTS. When I try to save or export a file I get a weird display issue where the diaglogs are not displaying correct, please see attached image.
![darwio_export_saving_issue](https://user-images.githubusercontent.com/25517972/127193935-c669f110-1e12-41fa-a347-a10d820cc0d3.png)

The application has all the permissions set to yes, or able to access.

**Comment by mararad** [comment] 2021-08-04 10:05
The same reported here: https://github.com/jgraph/drawio-desktop/issues/536

Duplicate of https://github.com/jgraph/drawio-desktop/issues/368

The problem is specific to the snap package.

**Closed as completed by mararad** 2021-08-04 10:05 UTC
