### ISSUE TITLE
Theme settings are not saved after the app is restarted

### ISSUE THREAD

**Issue by valamorgon** [jgraph/drawio-desktop#630] opened 2021-06-18 17:49 UTC
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I have two laptops that I installed the drawio desktop app.
One of them has Manjaro KDE, and theme settings work just fine.
Other has Manjaro XFCE with Compiz installed which is not saving the theme settings. It is stuck at "Automatic" theme.

**To Reproduce**
1. Go to Extras > Theme > Dark
2. Restart the app

**Expected behavior**
Selected theme should be applied after drawio io desktop app is restarted.

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version: 14.6.13

**Desktop (please complete the following information):**
 - OS: Manjaro XFCE (compiz installed)
 - Version: 21.0.7

**Additional context**
I tried both from AUR: https://aur.archlinux.org/packages/drawio-desktop/
and from: https://github.com/jgraph/drawio-desktop/releases/tag/v14.6.13

**Comment by neodon** [comment] 2021-09-14 16:33
I am now seeing this after updating from 15.1.3 to 15.2.5.  I have tried:

- Uninstalling and reinstalling 15.2.5 (theme is NOT saved on restart)
- Uninstalling 15.2.5 and reinstalling 15.1.3 (theme is saved again on restart)
- Uninstalling 15.1.3 and reinstalling 15.2.5 again (theme is again NOT saved on restart)

I'm currently forced to stick with 15.1.3 due to this bug.

OS: Windows 10 Pro Build 19041

Edit: It's also broken on MacOS.

**Comment by davidjgraph** [comment] 2021-09-14 16:34
We're pulling and doing a 15.2.6

**Comment by tepsley** [comment] 2021-11-17 10:22
Seeing this behavior still in 15.7.3 on
OS Name: Microsoft Windows 10 Enterprise
Version: 10.0.19043 Build 19043

**Comment by laellsr** [comment] 2022-01-26 16:11
`sudo chmod 777 -R /opt/drawio/`

It worked for me.
The problem is that my user is not allowed to save the theme settings.
Only root acess.

OS: Pop!_OS 21.10
Version: 16.4.0

**Comment by scockman** [comment] 2022-04-24 00:07
Seeing this behavior still in 17.4.2 on
OS Name: Microsoft Windows 10 Pro
Version: 21H2 Build 19044.1645

**Comment by m-mohamedin** [comment] 2022-05-12 17:26
@scockman  We couldn't reproduce on Windows, can you give us more details about how draw.io is installed and your account type on windows.

**Comment by scockman** [comment] 2022-05-12 17:34
@ashrafteleb I just now checked it and an update to version 18, appears to have resolved the issue. I can now switch between themes and the changes will apply after each restart. 😄

**Comment by m-mohamedin** [comment] 2022-05-12 19:40
I'll close this issue since new versions seem to fix it. If you still have the same issue, please reply to re-open

**Closed as completed by m-mohamedin** 2022-05-12 19:40 UTC

**Comment by Sannyasin** [comment] 2023-11-25 18:53
**Draw.io 22.1.2**

The problem remains in Windows 10 Pro
Version 10.0.19042
Build 19042

**Comment by davidjgraph** [comment] 2023-11-25 19:19
If there is a new problem please create a new issue.
