### ISSUE TITLE
Export to image not working - Windows version

### ISSUE THREAD

**Issue by Scorch-git** [jgraph/drawio-desktop#677] opened 2021-08-19 04:15 UTC
* [X ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When trying to export a file as a PNG or JPEG via File - Export or File - Export -  Advanced I get a popup saying Error -- Error saving file. Version 14.9.6

**To Reproduce**
1. Open an existing Diagram
2. Click on File, export as, PNG
3. Select Export
4. Select a folder and select save.
5. See error

**Expected behavior**
I expect I can save the drawio file as an image

**Screenshots**
![drawio error](https://user-images.githubusercontent.com/15829136/130006625-28102072-0f6b-429b-8c01-22d1e554bb20.jpg)

**draw.io version (In the Help->About menu of the draw.io editor):**
14.9.6

**Desktop (please complete the following information):**
 - OS: Windows 10 64Bit

**Additional context**
I just updated to the new version.

**Comment by davidjgraph** [comment] 2021-08-19 08:36
I can't repeat with this version and environment, anyone else see this?

**Comment by mararad** [comment] 2021-08-19 12:33
I am not able to recreate this. I use draw.io 14.9.6, Win 10 Pro and export is working fine.

* If you click File > Export as > Advanced > PNG does it help as a workaround?
* Could you attach the diagram file in question? You mentioned that you "Open an existing Diagram" first.
* Could you record a video showing all performed steps

**Comment by Scorch-git** [comment] 2021-08-20 02:01
It doesn't work when creating a new file either. Here is a video of that.

https://user-images.githubusercontent.com/15829136/130167251-256d21a0-20d5-43c3-8928-ab57ce1a7c1c.mp4

**Comment by mararad** [comment] 2021-08-20 10:31
Thanks. I followed your steps and all was working well at my place. Not able to reproduce this.

**Comment by davidjgraph** [comment] 2021-08-21 07:36
Can you save at all from the app? i.e. does saving a normal diagram work?

Is it some kind of permission issue to the specific folder you're selecting? Does any folder choice work?

**Comment by Scorch-git** [comment] 2021-08-22 23:56
I can save the diagrams in their native formats to any location, however, I am unable to export to any folder. There are no permission issues.
I will uninstall and reinstall to see if this fixes the issues. This could just be a weird edge case.

**Comment by Scorch-git** [comment] 2021-09-09 04:24
> I can save the diagrams in their native formats to any location, however, I am unable to export to any folder. There are no permission issues.
> I will uninstall and reinstall to see if this fixes the issues. This could just be a weird edge case.

Reinstalling didn't do anything. 
Interestingly, I did an install on another windows laptop (which had never had the software installed on it) and it works fine.

**Comment by davidjgraph** [comment] 2021-09-12 15:15
Could you start the machine in safe mode please? We would need it tested with the processes normally started at startup left off. Just export then work correctly?

**Comment by michal037** [comment] 2021-10-12 18:57
The program correctly exports the scheme to the image to the directory: `C:\ABC\abc.drawio.png`
The program fails for my desktop directory: `C:\Users\michal\Desktop\abc.drawio.png`

I ran the program as system administrator. 15.4.0 x64 [system install]

**Comment by davidjgraph** [comment] 2021-12-01 13:56
Closing as we cannot repeat.

**Closed as completed by davidjgraph** 2021-12-01 13:56 UTC
