### ISSUE TITLE
Drawio Export to JPEG/PNG show black boxes instead objects

### ISSUE THREAD

**Issue by Savemech** [jgraph/drawio-desktop#164] opened 2019-09-26 12:45 UTC
Subj
Got this 
![image](https://user-images.githubusercontent.com/8943498/65688885-88f38680-e074-11e9-814f-d56054d7b9aa.png)
Instead of this:
![image](https://user-images.githubusercontent.com/8943498/65688960-a9bbdc00-e074-11e9-998d-9a2581f9b6dd.png)

**Comment by Savemech** [comment] 2019-09-26 12:46
Using version 1.13.0
At 1.11.x all were good

**Comment by davidjgraph** [comment] 2019-09-26 12:52
I don't understand the versioning, what is 1.13.0?

**Comment by Savemech** [comment] 2019-10-19 13:54
Oh, I were wrong, that all were works on 10.x.x, but on latest version(12.1.0) I see these boxes instead of pictures on export to jpg/png

**Comment by davidjgraph** [comment] 2019-10-19 13:55
What is the diagram XML that reproduces this? What operating system are you using?

**Comment by Savemech** [comment] 2019-10-24 12:59
> What is the diagram XML that reproduces this? 
How can I get this diagram? Just export as XML?

It is MacOS X, and i start seeng this at mojave, and now on catalina

**Comment by Savemech** [comment] 2019-10-24 14:01
This is example file with exports with those boxes
http://bit.ly/32EMKWJ

**Comment by Savemech** [comment] 2019-10-24 14:03
the link is heading toward bitly, then to dropbox to understand when i hit limits and Dropbox start rising questions against my account

**Comment by alderg** [comment] 2019-10-30 13:45
Could you share an XML file that contains one image which exports like this, please?

**Comment by Savemech** [comment] 2019-11-05 19:25
it is right there http://bit.ly/32EMKWJ

**Comment by Savemech** [comment] 2019-11-05 19:34
```
<mxfile host="Electron" modified="2019-10-24T13:02:55.292Z" agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) draw.io/12.1.0 Chrome/76.0.3809.139 Electron/6.0.7 Safari/537.36" etag="QAXLEVNNZbzVngilrGcT" version="12.1.0" type="device" pages="1"><diagram id="D7GRicSkCPwuijYtu_RJ" name="Page-1">3VpZd6LaEv41eUwvxiQ+KqCh241thCT6cheCQZDBIyjDr79Ve4PikLbTJ6fPkG5XYA+1i6rvqwFzIypRMdjY6yVJ3EV4I3BucSOqN4LA88ID/MKRko0IIiewEW/ju/Wqw8DErxb1IFePbn13kR4tzJIkzPz18aCTxPHCyY7G7M0myY+XvSXh8alr21ucDUwcOzwfffHdbMlGH4T7w/jjwveWzcn8XYfNRHazuH6SdGm7Sd4aErUbUdkkScauokJZhGi9xi5sX/+d2b1im0Wc/cwG6/lZ0Ud/aLwf//E/eROMbt/MW5FJ2dnhtn5gRQcRilrrnJWNITbJNnYXKIu/EXv50s8Wk7Xt4GwOvoexZRaF9XRozxdhz3ZWHt2mJGGygak4iWF9780Pw2boRhAVpQ8/MO5tbNeHp2nNdeCHzr0lcVajQ7iDezv0vRhuNsz27MTvSepnfoLjDshZgJDebrHJfPDn8GTBPMmyJGot6NYSs2TdnFc/fW1qXLgo3rU+v/cpsGGRRItsU8KSeoN8J36R2aaaCreiWEMlbwGLryUv26C6awBdg9nbiz/4Gy5ql3/A/dKZ+8/8DrBd46UfUaZct+c7vgdnvtGfd01up2vG4De/QKD16JHdZpRrRuB6mWXI/y4+vdBPF4tVmHjJFwcUEPp0UYoohg/EBSfZbtLFLa64lYRup//A9yThtr3ryzr2QPxn+Pn+/sTL/MOZl3mO/8JdcjTH/UWOlv8Tjg4W8cqP0y9+0nYzOjE9zN4W7evas63wgUb+FFffN5F972ru3NUP3JfO3e/09N0FT9+FGCLTtR0fufzujy0mH2qc2zc78sOSmhpUu7OjNbWSKEoY2hfhboGePJuhq5VLe+yNb4fvr09tcE+62PhvOEQnqB4p9RJqwa2Lg45w5bHf8mm5IYN1cJSm0v1dYy2Z2gtGVLzG02U0iYyAurKW369tUPFLYoSDGOaV/cxhgjllP8G4iLeMCHD1Dh9xTc1IXHSRk43YhpdtaYyZuAK5iTM1O3GI8RMH2wzFGe4wSu8ZT+Gq29gEOPi2STwWk+EuX99CLM6YFYX+dh0mtpvSa4Hj7+kFzyxqb7LyzXayZFNS+uJRLRsyzv6Ml/ZTewcdWCwjj/crH2QJ03MjqDzMsADeTDBm7yfF+9ammt+H07kDSpDn+wmvpcQphujtHkjtwWN41+vOeMCojkmRsr0hzUmsBwNmxxXbZgHEs+d0AdJxnfhxRmOT3LuRVeTzNkvSOoS2CrBw8Za9G+lBCcePPRNv1Fvpk+LunXAcd+ULhVQTm9tBV/irYu79fyO7Hvh6xNYDV2umUp6esfRTfFvz8FoBRXn3+3Lqw+/zb90i/WnXunZmg2frCN1PdxBGewXQXVC+PxrCrOxJ85di61Scbz8+cY6a7IaiK7qlLJJS3jmRsyNBNydKp3Ijx9cfl9l8IFejeJnaL/Lm++Rr4j4+5SP/YQe7xGHsVMOoU87Kh2JkruShyNbpfnPOurKFZ24qeB09WnLuY/duWHZgp7OdRp1k9sKvpy9yMBee1vMIxoRONhSNzez1KbCVztYpdc8VwpU7gP3BWDYeexLIhn1hbD+OcYw3XumYYL88i+OoI32f6Lmudj1DXXG6CvMTkBE9l44Q7uYB55OJVOiBFOnicjkqu56udB/0CZfpmhvOYd309WnnBIlnCVnoDoxEV8mW+FKpK548Mr3q26Sb6YOPPks3G5rHZ7qDkJsPLPDPfNCJ51W+O4x89Q1paqa4zvs+eAodgcDoWPwagnbhTOmJ9utTovcb6dLDUGhWne6dxaej9KMW+RRlDMIVeJVeD03N1wdg1RWXD1WtMCp48gr+lT1CwLujiSSjl41JXhATPB/QWc9UNRzf4tzItFKiwHolz3UtP5ejHO998fXdd38aLAbaPdMr380Gz5FTHVsLkLueqZxvDfrxbMIV4PHKffy6swULkCXv5pEFaDU4J+psZhNetF+eOFtFb+veLArTOVzPo8521twrfOm+FCE8ewjo2ILXViizRuud+xjmM5PzzWdjPH1xwxPE1NZ1PPsF7BW5a3dQLKdhJ50L7u4dOWT6GobOyi3n4nMOa0DX/tYRZsA6rqPHTyWgp5oP+txs4mWksuQhMlFFNube0CQCUSR2r3bXl/Sp/RrXPo2J2QWbMLkzYOkc9ACbLeexkSKOvqktn1ZWqquWZJSSYARTwVC9NdgzmIKNvqlaqitc8W3S6Fws3YEFeDnZr3D8SHW2dH8wlk7Xt/SHs7o1XlbCt4l+CaHKJUs7heFfW31uBy8bC8XaeewBd35qN/s8zF/6lV0jj11zZdu786ifoXcd8Jqt6jgX2S9FCqeKNrB5dvXJzp708bmaTSB6DsKtXa0TJ3qOIKIF9AQFcf/wAf2HAr90hPQDOxqeHZ7oI+c1u2eVhjE5m74amDN4J8oTnemSEX/lHzH+2gc9+UMUE36k1Kg1PUDW0f37TPmRFw544wwF8gc7L5qLXzN4nlNU86TS96g2KocbmaS6juofWZL5u4f4NSCTFcOAckUaQfwcmeOaY9MSYiwHXNsa6rgALcqhqovASW6kahUJphCbxzncSyQgwFVYi/w0HckILF7XCEfgnqgayLCEIWZLyHSEWs7ySLXihoEjjtQpb5Sw15xuSaALdK9KZMikshE4F+TmENtBbjWWQSf+XCcNsjLEDRVlkZSAjCHEC2KS0vAx13TheSHeoR7Kmc4yeJc3TMwfXflUZ9AVztVEmC2If6qzB3nHyll8m6ZgMxHu2fNN4NzA245UT8ZMZfh5aVQrsKuHdhXgmQqas1jMEiGvyUaDskD3xiUH85pEmF84mJdAL5DVpfNgK96oNBYr/RxyogeyLR7jH+i1JaZFKyj0L+ZLsCtX+7cEXdHfiDI4twvP5/E0e1Y6h/4fqRbsd7A6keBcqORAr2rM9EIfTCTRQNmql8I6aYhVE9Wjy1EsmRrKKk51/iHu/HacGAuHyKcHTysiPIFv38mDpj3o5zOryYMfiC+tmABVQvXneD26xmvT4sGjkNk8gZQ5erAwgm4JnvmlmHJcddEqizKIZUEHPQvM2FscznVYJWV65TCYSsBGrLwoKom6QuRUNSoLY49KyrQcqjC4JxfljUytybwisDrX+4nfrgINrBoGs/V8kHd03+iTYAysXWF1xapNdc0tXntYORkWbyRTuH4Sv+7c164//BWfKJ34Q/ngLNdY5ZVqqsQIAsxFpudDBaOLJhCMPuUHc9ElLMU9wIvHQ57Y/cpzDAXnlxhwqG8gxl2p83TgvAWxS8NY3SBZ+mEd+TEkl4DSJjYUDMlaCbXkSYzvyhDLBNoXBBBnVRYrIcY3qMaYB3v1Yp/BA42xAGLrkMkXyOQSar02agfjaqZBLP4Ho3Z6rQd4B7Ue9AOfhlqBnPZfvw+1wfgKaiHTqZ6EmR6eHhCjQ9by/hxnH+lTe+gB09TlugvFqqRGKIuVtFMNVtt6dl8N1HGzjruOaDAEl7QaAFZBJgZZHlYDoK9TjWqE0+yJVYxKKyJZV/W66qLVQ52VV1Qe8bvIVpnFdNAJMjpUGph9aVYGdnDArALYAmdhTIeMjefiP1PD+V9/rlNWIYParOJoBfdPZpX0D8gFIvn7ckGlX8sFWGtjvBbA+x6gtWaWBej4LGZ168oF6lWI+Vgz00pDy0XiS5xB0adBX6AJEOehWnGwwoBadSpjjKc1tLpCVghDVgcjK6AHkThWX1slZYUv1QyEWpXWprTuL0/lmmr38E7qFOHV+F9W7TjC35I3Lvh3ZEK3G3hVXUme5XDwl2hUFnsneJr/aY1A5djHvYQj/et6CYlc6yWCMSCZ5AZ0VgQrMEUqgXHSJ/YSJxUY7QPq3oKcV1RnOQH100EnyAkldnrYUWKXqUvQcQOiQHZFQF/IJ6YHrB7jO45yNIF+CLrPEVuLXbEI58hN94lvHWBtTnsX2tmOEZlNZ3taBcL9KmedPXTvk7Oq7zQH//CZX3y9HZMlqHT2b4J1bqaO6dsG3XPq9/yj+El2BhbYkjctYbl0Bs+PTtThnb8tlo/UaxUSqbBfB8+IJMD3t7pUIwu6Q/JZyCoALfuOseYt3HfF484Vu2WrZG/doN43pxLle4Uo6alQuWHVQd/LQA8CSJhuGUoACaqT43sYVsFMT+M+vs+oWB8xls5je91nMF1aeafuei90uBAX/9kx/yMR6SfXXtXhR3LemTuT2V5X5TtHnMXfPfyiFP8f/THW/ed8b8wLF744vvDnWJ378++NOx//2vim/nOMw1zrDzFE7f8=</diagram></mxfile>
```

**Comment by alderg** [comment] 2019-11-06 05:30
This works for me.

**Comment by Savemech** [comment] 2019-11-06 08:49
Somehow doesn't work for me 
https://www.youtube.com/watch?v=O3eBmhleoPc

**Comment by alderg** [comment] 2019-11-06 10:00
ah yes, see it now in desktop.

**Comment by alderg** [comment] 2019-11-06 13:47
This will be fixed in the next release.

**Closed by alderg** 2019-11-06 13:47 UTC

**Comment by davidjgraph** [comment] 2019-11-07 11:38
Fixed in https://github.com/jgraph/drawio-desktop/releases/tag/v12.2.2

**Comment by Savemech** [comment] 2019-11-08 08:15
@davidjgraph @alderg 
Many thanks! Fix works for me! 🎉

**Comment by TechGeek01** [comment] 2021-05-12 05:44
I'm seeing this exact same issue in v14.1.8, running Windows 10
![Screenshot 2021-05-12 00_44_25-Home Network png ‎- Photos](https://user-images.githubusercontent.com/3240812/117924362-3d2e3900-b2bb-11eb-8370-108b9ed673eb.png)
