### ISSUE TITLE
new diagrams won't appear in the recent list

### ISSUE THREAD

**Issue by lvmm** [jgraph/drawio-desktop#963] opened 2022-04-21 08:49 UTC
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
Existing opened diagrams are added to the recent list, new diagrams saved using 'save as' command are not. This is highly confusing and causes heart-stopping buttock-clenching "all my work is gone!!!" moments.

**To Reproduce**
Steps to reproduce the behaviour:
1. create a new diagram
2. save it as a local file
3. close draw.io
4. reopen draw.io
5. open recent list (file-open recent) - the diagram just saved is missing from the list

**Expected behavior**
Newly created diagram saved using save as should be added to recent list

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 17.4.2

**Desktop (please complete the following information):**
 - OS: windows 10

**Additional context**

**Comment by mararad** [comment] 2022-04-21 09:30
Reproduced in 17.4.2 and Win 10 Pro.

1. Create a new diagram
2. Save it as a local file (File > Save as and/or click orange "Unsaved changes. Click here to save"
3. Close draw.io
4. Double click draw.io > Create New diagram
5. File > Open recent - the diagram just saved is missing from the list

Then if you reopen app again > Open existing diagram > choose the file > file is opened in the editor and also added to the list in File > Open recent

It looks like a diagram should be opened once as "Open existing diagram" in order to be visible in recent list

**Comment by m-mohamedin** [comment] 2022-04-21 20:55
Will be fixed in the next release
Thanks for the report

**Closed as completed by m-mohamedin** 2022-04-21 20:55 UTC
