### ISSUE TITLE
PDF Export Issue: Incorrect Font Color in Shapes

### ISSUE THREAD

**Issue by whitesh2p** [jgraph/drawio-desktop#1626] opened 2024-02-06 01:36 UTC
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
There is an issue with PDF export in draw.io where the font color does not print correctly for shapes created. Up to version 22.1.11, there were no issues with PDF export, but in the latest version, there is a problem with the font color changing.

**To Reproduce**
1. First, create a shape in draw.io with a black background and white text.
![image](https://github.com/jgraph/drawio/assets/9863473/d33eaa0d-2c82-4892-ac45-fd0745c504c6)

2. Click on File > Export as > Advanced.
![image](https://github.com/jgraph/drawio/assets/9863473/819eb5ca-c32c-4061-979c-59d76d3c35f9)

3. Export the PDF with the following settings:
- Format: PDF
- Background: unselect Transparent
![image](https://github.com/jgraph/drawio/assets/9863473/21a8b355-f7d2-41f8-98d2-3d3eb6ffbba3)

4. You can see that the text color is not white but gray.
![image](https://github.com/jgraph/drawio/assets/9863473/12201c8c-1c2a-473c-9b94-9f5bddc51447)

**Expected behavior**
Below is a PDF output from version 22.1.11.
![image](https://github.com/jgraph/drawio/assets/9863473/fea9713d-1b63-4139-95ae-09dd4b1178ca)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 23.0.2

**Desktop (please complete the following information):**
 - OS: macOS Sonoma Version 14.3

**Comment by alderg** [comment] 2024-02-06 10:48
We can't repeat this.

**Comment by whitesh2p** [comment] 2024-02-10 15:49
Have you tried this on the macos desktop version?
It works fine when checked on the web version, but the macOS desktop version has the same bug as described above.

**Comment by davidjgraph** [comment] 2024-02-11 10:52
This is the online repo, an issue with the desktop version needs to be reported in the desktop repo. The PDF exporters are entirely different between the two.

**Comment by gblomqvist** [comment] 2024-02-11 12:11
Duplicate of #1576.

**Closed as completed** 2024-02-11 12:15 UTC

**Comment by AndreaLombardo** [comment] 2024-02-14 14:54
Hi, version 23.0.2 desktop on Mac, still have this issue.
