### ISSUE TITLE
Attempting to update gives error on Ubuntu 18.04

### ISSUE THREAD

**Issue by DragonMeme** [jgraph/drawio-desktop#215] opened 2020-02-10 00:44 UTC
Attempting to update draw.io gives the following error:
```
Error occured while fetching updates. Error: ENOENT: no such file or directory, open '/opt/draw.io/resources/app-update.yml'
```

I am aware that there is no `resources` folder in `/opt/draw.io`
Current draw.io version: 12.5.3 attempting to update to latest version.

**Comment by davidjgraph** [comment] 2020-02-10 09:14
Duplicate of https://github.com/jgraph/drawio-desktop/issues/138

**Closed by davidjgraph** 2020-02-10 09:14 UTC
