### ISSUE TITLE
Copy as SVG

### ISSUE THREAD

**Issue by Yelfive** [jgraph/drawio-desktop#628] opened 2021-06-16 13:33 UTC
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

I recently need to use SVG to embed to my HTML, mainly because SVG is much smaller than an image and it is a vector. I know I can export the diagram as SVG and open it with vs code and then copy it manually. Still, it would be great help if I can just copy diagram as SVG directly.

> I'm using Mac Desctop 14.6.13

**Comment by davidjgraph** [comment] 2021-12-21 11:37
Duplicate of https://github.com/jgraph/drawio/issues/863

**Closed as completed by davidjgraph** 2021-12-21 11:37 UTC
