### ISSUE TITLE
When reopening the saved file, the shapes for Cloud disappears

### ISSUE THREAD

**Issue by YZJ2016** [jgraph/drawio-desktop#800] opened 2021-11-25 01:09 UTC
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

I create a file of cloud and save it to local, when I reopen the file, cannot edit it with cloud view.
Cannot find any cloud shapes. 

**To Reproduce**
1. Go to 'File'
2. Click on 'New'
3. Click on 'Create New Diagram'
4. Click on 'Cloud-->AWS', and Choose any diagram ，create it.
3. Save the file to local
4. Find the file in the local,and reopen it with drawio, you will never find the shapes for cloud diagram.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/22463594/143333754-603a76b8-7c3b-426f-96f9-8a93fd0ff52a.png)

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 15.8.4

**Desktop (please complete the following information):**
 - OS: MacOs

**Additional context**

**Comment by mararad** [comment] 2021-11-25 13:32
We are not able to reproduce the issue. Is it possible to attach video showing all steps?

**Comment by YZJ2016** [comment] 2021-11-25 14:08
@mararad  please check the video。

https://user-images.githubusercontent.com/22463594/143455914-ac6a4a22-a7ae-429d-afe6-9d6d44a80d0e.mp4

**Comment by davidjgraph** [comment] 2021-11-26 09:24
Are those libraries open in the app before you close it? I cannot see from the video.

**Comment by YZJ2016** [comment] 2021-11-26 10:32
Yes,all libraries are open.I recorded another video. Please check

https://user-images.githubusercontent.com/22463594/143566918-0c054255-5322-4420-b661-e503eb77508e.mp4

 .

**Closed as completed** 2022-12-14 11:54 UTC
Labels: wontfix
