### ISSUE TITLE
Bug: Opening Draw.io (Desktop-Version) opens two programs

### ISSUE THREAD

**Issue by oMrSmith** [jgraph/drawio-desktop#876] opened 2022-01-21 14:14 UTC
![image](https://user-images.githubusercontent.com/78870770/150541582-e51dc4b6-660d-401b-932a-a447971e7863.png)

The program even proposes to get the desktop-version
although that is the version that has been started.

**Comment by davidjgraph** [comment] 2022-01-21 14:20
Duplicate of #860

**Closed as completed by davidjgraph** 2022-01-21 14:20 UTC
