### ISSUE TITLE
CLI CSV Import Option/Feature

### ISSUE THREAD

**Issue by exwhyz** [jgraph/drawio-desktop#591] opened 2021-05-19 14:50 UTC
It would be a great CLI feature to add a CsvImport option that will allow direct rendering from the CLI without opening the draw.io GUI and manually entering the CSV using the Arrange > Insert > Advanced > CSV. Something along these lines:

`$ draw.io -CsvImport <MY_CSV_FILENAME.csv> -c <MY_CLI_GRAPH.drawio> -o <MY_GRAPH.jpg>`

**Comment by sailhobie** [comment] 2021-05-30 14:02
Agree! I'm trying to figure out the best way to maintain and update a diagram that is based on database info. Currently, in visio it is linked to a database and I hit refresh. I would like to switch to draw.io but seems like the only was to achieve similar result is to generate a csv for the data, append to the header info, and the copy and paste through the GUI each time I want to refresh. If there was a CLI I could just have a script run on a cron job and always be updated.

Maybe there is another solution I'm not aware of?

**Comment by MichaelCropper** [comment] 2022-10-25 12:15
Upvote from me for this feature request. Any planned timeline for this feature?

**Comment by m-mohamedin** [comment] 2022-11-14 21:53
Will be added to next release
Duplicate of #202

**Closed as completed by m-mohamedin** 2022-11-14 21:53 UTC
