### ISSUE TITLE
Install conflict (rpm) with other Electron app (balenaEtcher)

### ISSUE THREAD

**Issue by skipperTux** [jgraph/drawio-desktop#212] opened 2020-02-03 09:14 UTC
- **draw.io Desktop Version:** 12.5.3
- **OS Version and architecture:** Fedora 31 x86_64
- References: [balenaEtcher Issue 3051](https://github.com/balena-io/etcher/issues/3051#issue-558944168)

**Steps to Reproduce:**
If you try to install `draw.io-x86_64-12.5.3.rpm` when [balenaEtcher](https://github.com/balena-io/etcher) (rpm) is already installed on your system, you will get the following error message

```bash
Running transaction check
Transaction check succeeded.
Running transaction test
Error: Transaction test error:
  file /usr/lib/.build-id/3c/a310025e6d72d037f1fe23888c08317ff5c5f7 from install of draw.io-12.5.3-267.x86_64 conflicts with file from package balena-etcher-electron-1.5.73-1.x86_64
  file /usr/lib/.build-id/3e/0326bc2ef360cbd8a9d39169b3cffed688d09f from install of draw.io-12.5.3-267.x86_64 conflicts with file from package balena-etcher-electron-1.5.73-1.x86_64
  file /usr/lib/.build-id/40/b87885166f5ef16d1873ab3a91c5c8113a7657 from install of draw.io-12.5.3-267.x86_64 conflicts with file from package balena-etcher-electron-1.5.73-1.x86_64
  file /usr/lib/.build-id/43/403913e1ccc0475b5e2d1d2ddca551b8815a99 from install of draw.io-12.5.3-267.x86_64 conflicts with file from package balena-etcher-electron-1.5.73-1.x86_64
  file /usr/lib/.build-id/ab/b8ed97d406d9d9dda07e51af4fdf18fb3f5437 from install of draw.io-12.5.3-267.x86_64 conflicts with file from package balena-etcher-electron-1.5.73-1.x86_64
  file /usr/lib/.build-id/e4/d702c06d6d2db24de306bdf36168f02207268b from install of draw.io-12.5.3-267.x86_64 conflicts with file from package balena-etcher-electron-1.5.73-1.x86_64
```

See also cross-reference [Issue 3051](https://github.com/balena-io/etcher/issues/3051#issue-558944168) at balenaEtcher.

**Current workaround:**
Install at least one of those applications as AppImage.

**Comment by vk5tu** [comment] 2020-05-14 16:23
Similar issue with Electron application signal-desktop for Fedora, installed using the 3rd-party RPM packaging at https://copr.fedorainfracloud.org/coprs/luminoso/Signal-Desktop/

```
$ cat /etc/fedora-release 
Fedora release 32 (Thirty Two)

$ rpm --query signal-desktop
signal-desktop-1.33.4-1.fc32.x86_64

$ sudo dnf --assumeyes install https://github.com/jgraph/drawio-desktop/releases/download/v13.0.3/draw.io-x86_64-13.0.3.rpm
Last metadata expiration check: 2:13:08 ago on Thu 14 May 2020 23:39:03.
draw.io-x86_64-13.0.3.rpm                       3.9 MB/s |  69 MB     00:17    
Dependencies resolved.
================================================================================
 Package         Architecture   Version              Repository            Size
================================================================================
Installing:
 draw.io         x86_64         13.0.3-298           @commandline          69 M

Transaction Summary
================================================================================
Install  1 Package

Total size: 69 M
Installed size: 267 M
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Error: Transaction test error:
  file /usr/lib/.build-id/5b/fbd3977f004574cd6668333fd1dc52e6b31010 from install of draw.io-13.0.3-298.x86_64 conflicts with file from package signal-desktop-1.33.4-1.fc32.x86_64
  file /usr/lib/.build-id/68/31304e78fc4f4cd1bd8216d99e32dabe4973c3 from install of draw.io-13.0.3-298.x86_64 conflicts with file from package signal-desktop-1.33.4-1.fc32.x86_64
  file /usr/lib/.build-id/72/d86eb8b1163969d3fc6f34b62b5160a33ad726 from install of draw.io-13.0.3-298.x86_64 conflicts with file from package signal-desktop-1.33.4-1.fc32.x86_64
  file /usr/lib/.build-id/75/2db195051aa513f5916d17ecc6e5d755124e14 from install of draw.io-13.0.3-298.x86_64 conflicts with file from package signal-desktop-1.33.4-1.fc32.x86_64
  file /usr/lib/.build-id/9f/604335c41e24151c5dbca16a33b81dc56c4c54 from install of draw.io-13.0.3-298.x86_64 conflicts with file from package signal-desktop-1.33.4-1.fc32.x86_64
  file /usr/lib/.build-id/cc/813d23c84126298d221a8a7c70184d3fca320d from install of draw.io-13.0.3-298.x86_64 conflicts with file from package signal-desktop-1.33.4-1.fc32.x86_64
  file /usr/lib/.build-id/cf/cca356ccaabf8d1e182054675cf63a92ad57a9 from install of draw.io-13.0.3-298.x86_64 conflicts with file from package signal-desktop-1.33.4-1.fc32.x86_64
  file /usr/lib/.build-id/e4/a4a2ce7ce0759262130adc2121ec9619cd9832 from install of draw.io-13.0.3-298.x86_64 conflicts with file from package signal-desktop-1.33.4-1.fc32.x86_64
  file /usr/lib/.build-id/f1/49c1b37a035c9c336c70bb56777811230332c9 from install of draw.io-13.0.3-298.x86_64 conflicts with file from package signal-desktop-1.33.4-1.fc32.x86_64
```

**Comment by jezekus** [comment] 2021-02-28 11:01
Hello,
I am having same issue on Fedora 33 and conflict is between VS Codium and draw.io. If any tests are needed, I am happy to test.

```
$ uname -a
Linux x270 5.10.16-200.fc33.x86_64 #1 SMP Sun Feb 14 03:02:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ sudo dnf localinstall https://github.com/jgraph/drawio-desktop/releases/download/v14.4.3/draw.io-x86_64-14.4.3.rpm
Last metadata expiration check: 1:46:16 ago on Sun 28 Feb 2021 10:12:46 AM CET.
draw.io-x86_64-14.4.3.rpm                                                                                                                                                                                                                          22 MB/s |  76 MB     00:03    
Dependencies resolved.
==================================================================================================================================================================================================================================================================================
 Package                                                          Architecture                                                    Version                                                             Repository                                                             Size
==================================================================================================================================================================================================================================================================================
Installing:
 draw.io                                                          x86_64                                                          14.4.3-1                                                            @commandline                                                           76 M

Transaction Summary
==================================================================================================================================================================================================================================================================================
Install  1 Package

Total size: 76 M
Installed size: 285 M
Is this ok [y/N]: y
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Error: Transaction test error:
  file /usr/lib/.build-id/14/512ca58e91f1940ba8e68d620c03e13cfb7d82 from install of draw.io-14.4.3-1.x86_64 conflicts with file from package codium-1.53.2-1613090035.el7.x86_64
  file /usr/lib/.build-id/1c/1eccea7fe32b13593eb32f999fc3ce90432239 from install of draw.io-14.4.3-1.x86_64 conflicts with file from package codium-1.53.2-1613090035.el7.x86_64
  file /usr/lib/.build-id/63/e57a96064e30d496ce9596cb5861ce64f52160 from install of draw.io-14.4.3-1.x86_64 conflicts with file from package codium-1.53.2-1613090035.el7.x86_64
  file /usr/lib/.build-id/66/c77539c4ab0def65c2f355188fe71bff7b602d from install of draw.io-14.4.3-1.x86_64 conflicts with file from package codium-1.53.2-1613090035.el7.x86_64
  file /usr/lib/.build-id/74/589964965a9efc95d3e4202f7fc6a7226b6e78 from install of draw.io-14.4.3-1.x86_64 conflicts with file from package codium-1.53.2-1613090035.el7.x86_64
  file /usr/lib/.build-id/76/90a7dcb40a4a052fdfb0f46a0dbeabbdf6df47 from install of draw.io-14.4.3-1.x86_64 conflicts with file from package codium-1.53.2-1613090035.el7.x86_64
  file /usr/lib/.build-id/a7/97d3b4a5fac6864fda3d230e3ac9104d624990 from install of draw.io-14.4.3-1.x86_64 conflicts with file from package codium-1.53.2-1613090035.el7.x86_64

```

**Comment by Daniel-Vaz** [comment] 2021-03-01 09:02
Same conflict issue here with VS Codium.

**Comment by davidjgraph** [comment] 2021-09-30 07:30
Closing due to lack of interest.

**Closed by davidjgraph** 2021-09-30 07:30 UTC
Labels: help wanted

**Comment by weyderfs** [comment] 2021-12-17 03:03
I guess that _issue_ come back at Fedora 34, after installed Draw Io starts to conflicts with another Electron installers such as Kotena Lens and Balena Etcher.

**Comment by davidjgraph** [comment] 2021-12-17 09:28
I've no doubt it's still an issue, but does anyone know how to fix it?

**Comment by uniuuu** [comment] 2023-03-05 06:18
Hi @davidjgraph 

Workaround has been posted here [rpm -i ./drawio-x86_64-20.3.0.rpm --excludepath /usr/lib/.build-id/](https://github.com/jgraph/drawio-desktop/issues/259#issuecomment-1271610653)

Possible solution is to remove those /usr/lib/.build-id/ links from the rpm package. [Proposed solution](https://github.com/jgraph/drawio-desktop/issues/259#issuecomment-717566841)

The issue is still exist. The **slack** conflicts with the **draw-io** when **draw-io** was installed first or **draw-io** conflicts with **slack** when **slack** was installed firstly.

Conflict errors:
```
dnf install ./slack-4.29.149-0.1.el8.x86_64.rpm 
Last metadata expiration check: 0:03:54 ago on Sun 05 Mar 2023 01:06:14 PM.
Dependencies resolved.
==============================================================================================================================================================================================
 Package                                  Architecture                              Version                                             Repository                                       Size
==============================================================================================================================================================================================
Installing:
 slack                                    x86_64                                    4.29.149-0.1.el8                                    @commandline                                     78 M

Transaction Summary
==============================================================================================================================================================================================
Install  1 Package

Total size: 78 M
Installed size: 250 M
Is this ok [y/N]: y
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Error: Transaction test error:
  file /usr/lib/.build-id/0d/9fad3f21b1e381cc66b5efcae8f3910ae0edc1 from install of slack-4.29.149-0.1.el8.x86_64 conflicts with file from package draw.io-20.8.16-1.x86_64
  file /usr/lib/.build-id/76/9d0269491ca2313fcd15d63059bac67bd8b1b3 from install of slack-4.29.149-0.1.el8.x86_64 conflicts with file from package draw.io-20.8.16-1.x86_64
  file /usr/lib/.build-id/c2/dcac7cb6a727685d10d4161a0d14988f12a0fa from install of slack-4.29.149-0.1.el8.x86_64 conflicts with file from package draw.io-20.8.16-1.x86_64
  file /usr/lib/.build-id/cb/dc9db5fec0e6129bddcb0c282be98be4c6966e from install of slack-4.29.149-0.1.el8.x86_64 conflicts with file from package draw.io-20.8.16-1.x86_64

```

Or with rpm:
```

rpm -ivh ./slack-4.29.149-0.1.el8.x86_64.rpm
warning: ./slack-4.29.149-0.1.el8.x86_64.rpm: Header V4 RSA/SHA512 Signature, key ID 7eb66c16: NOKEY
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
	file /usr/lib/.build-id/0d/9fad3f21b1e381cc66b5efcae8f3910ae0edc1 from install of slack-4.29.149-0.1.el8.x86_64 conflicts with file from package draw.io-20.8.16-1.x86_64
	file /usr/lib/.build-id/76/9d0269491ca2313fcd15d63059bac67bd8b1b3 from install of slack-4.29.149-0.1.el8.x86_64 conflicts with file from package draw.io-20.8.16-1.x86_64
	file /usr/lib/.build-id/c2/dcac7cb6a727685d10d4161a0d14988f12a0fa from install of slack-4.29.149-0.1.el8.x86_64 conflicts with file from package draw.io-20.8.16-1.x86_64
	file /usr/lib/.build-id/cb/dc9db5fec0e6129bddcb0c282be98be4c6966e from install of slack-4.29.149-0.1.el8.x86_64 conflicts with file from package draw.io-20.8.16-1.x86_64
```

**Comment by davidjgraph** [comment] 2023-03-06 09:42
OK, but how do we do that using electron-builder? We need a PR for this.

**Comment by sudeshjethoe** [comment] 2023-06-27 14:37
I still have this issue with version 21.5.0 and slack 4.32.127 on Fedora 38

**Comment by davidjgraph** [comment] 2023-06-27 14:49
"Me too" messages don't add anything, please only post here if you have a technical solution.
