### ISSUE TITLE
Memory Leak?

### ISSUE THREAD

**Issue by aaronbrighton** [jgraph/drawio-desktop#431] opened 2020-11-17 14:14 UTC
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Without having any active draw.io windows open, I noticed a draw.io process using up nearly 10GB of memory (all that was available) in the background, and appeared to be causing significant disk i/o.

I'm unsure as to what caused this to happen, however, this is the behavior of last time I used draw.io:

1. Opened draw.io (lag time opening, so accidentally kept reopening and ended up with 5+ draw.io instances)
2. draw.io asked to update, so I proceeded with the update while closing all the other draw.io windows inadvertently opened
3. After the update was complete I left all draw.io windows closed and didn't end up using it

The next day after logging into the computer (had been left on, though may have went to sleep), noticed the memory utilization in task manager.  Tried generating a dump file from task manager, however, it never completed even after creating a file 17GB in size... when I finally killed the process that dump file disappeared -- so unfortunately that's not available.

**To Reproduce**
1. See description above.  I have not at this time tried to reproduce the bug.

**Expected behavior**
After an update of draw.io and all windows are closed, draw.io should not have any lingering processes in the background and should not balloon or chew up disk as seen in task manager.

**Screenshots**

![image](https://user-images.githubusercontent.com/4945772/99400549-13202f00-28b5-11eb-87c1-4adc8aca204c.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- diagrams.net 13.9.9

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**

When I relaunched draw.io just now to check version, an update was applied (not sure if yesterday's update attempt failed) -- current version is 13.9.9 but the faulting version may have been older.

**Comment by aaronbrighton** [comment] 2020-11-17 14:15
Not sure if there is any relation, the only github issue I could find related to memory issues is from awhile ago and tied to the in-browser version: https://github.com/jgraph/drawio/issues/87

**Comment by KDCinfo** [comment] 2020-12-19 10:03
> Not sure if there is any relation, the only github issue I could find related to memory issues is from awhile ago and tied to the in-browser version: [jgraph/drawio#87](https://github.com/jgraph/drawio/issues/87)

My laptop just maxed out on memory. I had closed my Draw.io desktop app hours ago, and didn't realize it was still running in the background until I saw my flash drives flipping out. So I checked my task manager, and hard drive was 100%. Was able to close VS Code and my 60+ Chrome tabs, then I saw draw.io was at 11 GB of RAM and climbing; then 12 GB (it ate up what VS Code and Chrome released). I have 16 GB.

From the issue @aaronbrighton provided, this sounds like it's either an edge case issue or a random fluke; in any case quite intermittent, if not quite rare. Will be keeping an eye on it, but wanted to post here just in case it persists.

P.S. Draw.io is an awesome app!!

**Comment by Binstown** [comment] 2020-12-29 12:27
I have exactly the same issue as described:
![image](https://user-images.githubusercontent.com/7222102/103283557-c9a52280-49d0-11eb-8cbb-8ba0b66ee1bf.png)

I have no Draw.io windows open, and i have closed other apps.  Drawio mem usage goes up from 4gb to 5gb when i close firefox.

If I kill the Drawio.io task in task manager, when i reopen my Drawio files, i am prompted that there is a newer version of the file that i can edit.  When i edit it sometimes works, other times it says the file cant be opened, and i lose the contents.

**Comment by Rouves** [comment] 2021-02-14 21:55
Not a 100% certain but I believe I have run in to the same bug. Unfortunately I wasn't able to make a screenshot as draw.io basically used up all the ram(before Windows crashed: 27GB and all the Hard Drive bandwidth) . Attached is a Screenshot of the Event Log. Draw.io tried to use almost 200GB of ram.
![draw io event](https://user-images.githubusercontent.com/79062617/107890049-f082ce00-6f16-11eb-9b1f-0cfc1d1de245.jpg)

` <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
 <System>
  <Provider Name="Microsoft-Windows-Resource-Exhaustion-Detector" Guid="{9988748e-c2e8-4054-85f6-0c3e1cad2470}" /> 
  <EventID>2004</EventID> 
  <Version>0</Version> 
  <Level>3</Level> 
  <Task>3</Task> 
  <Opcode>33</Opcode> 
  <Keywords>0x8000000020000000</Keywords> 
  <TimeCreated SystemTime="2021-02-14T21:18:43.3904309Z" /> 
  <EventRecordID>7405</EventRecordID> 
  <Correlation ActivityID="{8ac4347f-0981-4b55-8eb2-a10f6311b72e}" /> 
  <Execution ProcessID="10836" ThreadID="20468" /> 
  <Channel>System</Channel> 
  <Computer>DESKTOP-N6C4L2R</Computer> 
  <Security UserID="S-1-5-18" /> 
  </System>
 <UserData>
 <MemoryExhaustionInfo xmlns="http://www.microsoft.com/Windows/Resource/Exhaustion/Detector/Events">
 <SystemInfo>
  <SystemCommitLimit>193604644864</SystemCommitLimit> 
  <SystemCommitCharge>193500545024</SystemCommitCharge> 
  <ProcessCommitCharge>187090423808</ProcessCommitCharge> 
  <PagedPoolUsage>692350976</PagedPoolUsage> 
  <PhysicalMemorySize>68662112256</PhysicalMemorySize> 
  <PhysicalMemoryUsage>67546075136</PhysicalMemoryUsage> 
  <NonPagedPoolUsage>1695174656</NonPagedPoolUsage> 
  <Processes>187</Processes> 
  </SystemInfo>
 <PagedPoolInfo>
 <Tag_1>
  <Name>SaFA</Name> 
  <PoolUsed>59485760</PoolUsed> 
  </Tag_1>
 <Tag_2>
  <Name>MmSt</Name> 
  <PoolUsed>40903744</PoolUsed> 
  </Tag_2>
 <Tag_3>
  <Name>NtfF</Name> 
  <PoolUsed>33427200</PoolUsed> 
  </Tag_3>
  </PagedPoolInfo>
 <NonPagedPoolInfo>
 <Tag_1>
  <Name>smNp</Name> 
  <PoolUsed>492220416</PoolUsed> 
  </Tag_1>
 <Tag_2>
  <Name>smCB</Name> 
  <PoolUsed>301010944</PoolUsed> 
  </Tag_2>
 <Tag_3>
  <Name>smBt</Name> 
  <PoolUsed>225103872</PoolUsed> 
  </Tag_3>
  </NonPagedPoolInfo>
 <ProcessInfo>
 <Process_1>
  <Name>draw.io.exe</Name> 
  <ID>17412</ID> 
  <CreationTime>2021-02-14T16:44:25.5375865Z</CreationTime> 
  <CommitCharge>97243877376</CommitCharge> 
  <HandleCount>240</HandleCount> 
  <Version>14.1.8.0</Version> 
  <TypeInfo>201</TypeInfo> 
  </Process_1>
 <Process_2>
  <Name>draw.io.exe</Name> 
  <ID>16916</ID> 
  <CreationTime>2021-02-14T16:26:33.8396126Z</CreationTime> 
  <CommitCharge>83879575552</CommitCharge> 
  <HandleCount>240</HandleCount> 
  <Version>14.1.8.0</Version> 
  <TypeInfo>210</TypeInfo> 
  </Process_2>
 <Process_3>
  <Name>firefox.exe</Name> 
  <ID>14000</ID> 
  <CreationTime>2021-02-14T14:26:03.2188133Z</CreationTime> 
  <CommitCharge>348385280</CommitCharge> 
  <HandleCount>2084</HandleCount> 
  <Version>85.0.2.7709</Version> 
  <TypeInfo>219</TypeInfo> 
  </Process_3>
 <Process_4>
  <Name /> 
  <ID>0</ID> 
  <CreationTime>1601-01-01T00:00:00.0000000Z</CreationTime> 
  <CommitCharge>0</CommitCharge> 
  <HandleCount>0</HandleCount> 
  <Version>0.0.0.0</Version> 
  <TypeInfo>0</TypeInfo> 
  </Process_4>
 <Process_5>
  <Name /> 
  <ID>0</ID> 
  <CreationTime>1601-01-01T00:00:00.0000000Z</CreationTime> 
  <CommitCharge>0</CommitCharge> 
  <HandleCount>0</HandleCount> 
  <Version>0.0.0.0</Version> 
  <TypeInfo>0</TypeInfo> 
  </Process_5>
 <Process_6>
  <Name /> 
  <ID>0</ID> 
  <CreationTime>1601-01-01T00:00:00.0000000Z</CreationTime> 
  <CommitCharge>0</CommitCharge> 
  <HandleCount>0</HandleCount> 
  <Version>0.0.0.0</Version> 
  <TypeInfo>0</TypeInfo> 
  </Process_6>
  </ProcessInfo>
 <ExhaustionEventInfo>
  <Time>2021-02-14T21:18:44.0129258Z</Time> 
  </ExhaustionEventInfo>
  </MemoryExhaustionInfo>
  </UserData>
  </Event>`

**Comment by dhoernel** [comment] 2021-02-19 13:02
I can confirm this behavior on my Windows PC: draw.io background processes take huge amount of memory while draw.io is not running anymore (version 14.1.8).

**Comment by druman-ff** [comment] 2021-03-12 23:02
Happened now to me, I didn't use pc for a while, then I went on youtube and my pc was very laggy.
ver 14.1.8
![obraz](https://user-images.githubusercontent.com/79249776/111007506-44a29600-838f-11eb-803e-19ead4e53b83.png)

**Comment by cfmjohn** [comment] 2021-03-20 15:49
I've just had the same problem - had draw.io running for about 24 hours, closed it down, then a few hours later Windows 10 was really struggling because drawio.exe was consuming all available memory.

I'd tried to update from 13.x (can't remember the exact version) to 14.4.3 but the installer went around in an infinite loop, completing successfully but always re-opening the old version. I think I uninstalled via Add/Remove Programs before updating to 14.4.3 via a fresh download, but the old exe may still have been running.

I've tried re-opening drawio and can't reproduce the problem. Is there any logging etc I can help supply if this happens again?

**Comment by douglasg14b** [comment] 2021-03-21 05:16
Same problem here. The memory hogging & disk thrashing continued even after the editor was close,d had to kill the process myself. I only had a diagram (Small) open for maybe 12 hours.

v 13.9.9

![image](https://user-images.githubusercontent.com/1400380/111894557-f1e95f80-89c8-11eb-8460-3a2c552d6fa7.png)

We're talking like 100GB pagefile usage 0_0

![image](https://user-images.githubusercontent.com/1400380/111894746-8a341400-89ca-11eb-9c36-f510ddabf556.png)

**Comment by lkwq007** [comment] 2021-05-13 14:44
It happened to me twice. I had closed drawio, but the process would not exit. Then, after several hours, MEMORY LEAK

![image](https://user-images.githubusercontent.com/1665437/118142199-bbfeaf80-b43c-11eb-9941-ca3df012d5db.png)

I am using `draw.io-14.4.3-windows-no-installer.exe`.

**Comment by Giuseppetm** [comment] 2021-06-05 20:00
Same problem here.

**Comment by hkayann** [comment] 2021-06-26 12:39
I have encountered the same thing.

**Comment by davidjgraph** [comment] 2021-11-30 11:41
We've never been able to repeat this. We'll close, if you find steps and environment that recreate for us, we can take a look.

**Closed by davidjgraph** 2021-11-30 11:41 UTC

**Comment by douglasg14b** [comment] 2021-11-30 18:54
This happens to me probably once every month or so. I have no idea what causes it. But it's annoying enough hat I know I can't keep diagrams open on my devices lest they become unstable.
