### ISSUE TITLE
Export As ...

### ISSUE THREAD

**Issue by GandalfUFR** [jgraph/drawio-desktop#899] opened 2022-02-03 08:41 UTC
When using often the "export as ..." function (for documentation purposes in my case) it would be helpful to be able ...

1. to save settings as preferences, e.g. PNG border width, selection only, transparency, etc.
2. to have the additional option to copy the PNG (or whatever format) to the clipboard so that you can paste it immediately into the destination document

**Comment by Griffon26** [comment] 2022-08-26 13:40
Is this a duplicate of #508 ?

**Comment by GandalfUFR** [comment] 2022-08-26 13:53
Yes, did not find the other one before creating my own one here, means you can merge ... or even better start working on it ;-)

**Comment by GandalfUFR** [comment] 2022-08-26 13:59
Since there is a similar thread already open: https://github.com/jgraph/drawio-desktop/issues/508
You can add your comment there so we can have all suggestions under one roof. Closing this here as it is a duplicate.

**Closed as completed** 2022-08-26 14:00 UTC
