### ISSUE TITLE
Custom web fonts not rendered in exported images

### ISSUE THREAD

**Issue by penyuan** [jgraph/drawio-desktop#484] opened 2021-01-31 14:58 UTC
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Custom web fonts are **not** rendered in exported images such as PNG, JPG, SVG.

**To Reproduce**
1. Create a diagram.
2. Add text to the diagram.
3. Set text to use a custom web font.
4. The custom web font is displayed correctly in diagrams.net
5. Export diagram to different images such as PNG, JPG, or SVG.
6. Open exported images in image viewer *or* web browser.
7. The text in those images are not using the custom web font. Instead they seem to be using a serif font I can't identify (Times New Roman??).

**Expected behavior**
The font for text should remain consistent between what is selected/displayed in diagrams.net and all exported images.

**Screenshots**
Here is the custom web font [Tecnico](https://fontlibrary.org/en/font/tecnico) being correctly rendered in a diagrams.net diagram: 
![correct_font](https://user-images.githubusercontent.com/13352427/106387622-80326380-63d2-11eb-8c1f-070f7f5aca85.png)

When the diagram is exported to bitmaps images (PNG or JPG) or vector images (SVG) the custom font is *not* rendered:
![wrong_font](https://user-images.githubusercontent.com/13352427/106387652-9d673200-63d2-11eb-8b3b-ebc86b4f7ad3.jpg)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 14.1.8 (installed from Flathub)

**Desktop (please complete the following information):**
 - OS: GNU/Linux kernel 4.18 on RHEL 8.3
 - Web browser: Mozilla Firefox 85.0

**Additional context**
1. I tried saving the diagrams.net diagram directly as `*.drawio.svg` and `*.drawio.png`, but with the same problem described above.
2. I tried checking *and* unchecking "Include a copy of my diagram" when exporting but that did not make a difference.
3. Internal/default fonts such as Comic Sans MS do not have this problem.
4. Choosing a system font also does not have this problem. 
5. If I export to PDF, then the custom web font is rendered correctly.

**Comment by penyuan** [comment] 2021-05-21 17:58
Any ideas on how to solve this problem?

**Comment by chipbite** [comment] 2021-09-07 12:36
Related to https://github.com/jgraph/drawio/issues/1702.
_(or duplicate of, but this issue is - IMO - alot more clear than 1702)_

**Comment by chipbite** [comment] 2021-09-08 08:07
* ✅ `PNG` seems to work, at least in my incidental usage. 
* ❌ `SVG` seems to not work. (you get a serif font, like times)

I am testing using the open font [Roboto](https://fonts.google.com/specimen/Roboto)

**Comment by penyuan** [comment] 2022-09-16 13:52
Is there any confirmation on whether this issue has been addressed by the developers?

**Closed** 2022-10-04 15:50 UTC
Labels: wontfix

**Comment by davidjgraph** [comment] 2022-10-04 16:26
It has not been addressed.

**Comment by bogdanbacila** [comment] 2022-12-08 10:54
I'm facing the same issue, just that it doesn't render it correctly in the PDF output.
