### ISSUE TITLE
v16 opening drawio file shows clean screen with new or open popup question

### ISSUE THREAD

**Issue by imrefazekas** [jgraph/drawio-desktop#838] opened 2021-12-18 17:05 UTC
**Describe the bug**
v16 can not open a drawio file. When opening it, it shows for a sec and shows again clean workspace and the popup to create new or open existing.
downgrading to v15, it works. Made the upgrade / downgrade 3 times, same result.

**To Reproduce**
1. Click on a drawio file

**Expected behavior**
Should open the content of the file.

**Desktop (please complete the following information):**
 - OS: MacOS 12.1, M1 macbook pro

**Comment by dvalter** [comment] 2021-12-18 22:24
I guess the same bug happens when I try opening a file from shell
`$ ./drawio-x86_64-16.0.0.AppImage /path/to/file.drawio`

**OS**: Arch Linux, x86-64, AppImage

**Comment by davidjgraph** [comment] 2021-12-19 14:28
I can't repeat on an M1 macbook pro, MacOS 12.1. Anyone else can see this?

Opening from command line is a different issue. Please search for existing issues or open another.

**Comment by JesseAldridge** [comment] 2021-12-19 21:37
I get the same behavior OP described. Either double clicking in Finder or opening from the command line. 
<img width="270" alt="Screen Shot 2021-12-19 at 3 37 55 PM" src="https://user-images.githubusercontent.com/191903/146691719-7c2adb02-2940-4347-8742-2c6d0c002500.png">

**Comment by missuor** [comment] 2021-12-20 03:23
Reproduced this problem Ubuntu 20.04

v15.8.7 is ok

**Comment by missuor** [comment] 2021-12-20 03:27
> 

v15.8.7 is ok

**Comment by keithbrink** [comment] 2021-12-20 07:32
Same issue, here is what it looks like when I double click from Finder:

https://a.cl.ly/12u0xXRP

**Comment by davidjgraph** [comment] 2021-12-20 09:52
OK, no more reports needed, thanks, we're investigating.

**Comment by m-mohamedin** [comment] 2021-12-20 17:09
The issue will be fixed in the next release
Thanks for the reports

**Closed as completed by m-mohamedin** 2021-12-20 17:09 UTC

**Comment by davidjgraph** [comment] 2021-12-21 23:06
Fixed in 16.0.2
