### ISSUE TITLE
14.4.2 check for update -> install fails to update installation

### ISSUE THREAD

**Issue by rcaf-anthony** [jgraph/drawio-desktop#523] opened 2021-03-05 21:46 UTC
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
attempting to install 14.4.3 when starting 14.4.2 fails and doesn't replace 14.4.2

**To Reproduce**
1. Have 14.4.2 installed on Windows Desktop
2. Start 14.4.2
3. get popup stating that a new version exists
4. click install
5. Go through install process
6. when application restarts it is v14.4.2 and the new version popup appears again

**Expected behavior**
v14.4.2 should install v14.4.3 and replace itself

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 14.4.2

**Desktop (please complete the following information):**
 - OS: Win10

**Additional context**

**Comment by davidjgraph** [comment] 2021-03-06 08:06
Duplicate of #518

**Closed by davidjgraph** 2021-03-06 08:06 UTC
