### ISSUE TITLE
svg file import ppt will display "Text is not SVG - cannot display"  

### ISSUE THREAD

**Issue by mini92** [jgraph/drawio-desktop#1265] opened 2023-03-23 03:22 UTC
### Preflight Checklist

* [ ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
svg file import ppt will display "Text is not SVG - cannot display"  

**To Reproduce**
1. Go to 'diagrams.net 20.8.16  draw svg'
2. Click on 'Ctrl +S  save svg'
3. Scroll down to '.'
![image](https://user-images.githubusercontent.com/13175278/227093819-63d2b99c-e071-4664-b327-74bbcf9f1252.png)

**Expected behavior**

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version x.y.z

**Desktop (please complete the following information):**
 - OS: Windows, MacOS, Linux...

**Additional context**

**Comment by davidjgraph** [comment] 2023-03-24 17:54
This is a duplicate of https://github.com/jgraph/drawio/issues/774. That thread explains the history of the issue. The solution of converting SVG labels is not possible on desktop because we do not connect to servers.

**Closed as completed by davidjgraph** 2023-03-24 17:54 UTC

**Comment by davidjgraph** [comment] 2024-01-26 15:48
23.0.2 now replaces the warning text with a high-res image of the label, if embed images and embed fonts are ticked in the SVG export dialog.
