### ISSUE TITLE
chrome-sandbox start-up error (with Debian package)

### ISSUE THREAD

**Issue by moseb** [jgraph/drawio-desktop#163] opened 2019-09-20 08:48 UTC
Is this a known problem?
```
$ drawio 
[4358:0920/104603.383086:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/draw.io/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap

$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.11 (stretch)
Release:        9.11
Codename:       stretch
```

**Comment by shoffmeister** [comment] 2019-10-17 10:29
This seems to be a duplicate of #150 - which has been resolved.

**Closed** 2019-10-17 10:30 UTC

**Comment by moseb** [comment] 2019-10-17 10:41
@shoffmeister #150 is about the the RPM package according to its title. This ticket here is about the Debian package. If #150 should be about both, can we adjust the title of #150 please?
