### ISSUE TITLE
When exporting an image to svg using the CLI support the --embed-diagram flag

### ISSUE THREAD

**Issue by steinwelberg** [jgraph/drawio-desktop#848] opened 2021-09-21 09:46 UTC
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I want to convert a large number of drawio files to svg format that also include the diagram.

**Describe the solution you'd like**
I'd like to be able to execute the following command:
```bash
draw.io -x -e -f svg -r -o /tmp/ /folder-containing-drawio-images
```

This command should convert my drawio files into svg files including a copy of my image. So I can use the svg both as image in a site and also for editing using the Web UI.

**Describe alternatives you've considered**
Alternatively I can manually import all the images one by one in the web UI and then save them as svg images.

**Comment by davidjgraph** [comment] 2021-12-26 08:40
Duplicate of #382

**Closed as completed by davidjgraph** 2021-12-26 08:40 UTC
