### ISSUE TITLE
unable to modify the configuration properties

### ISSUE THREAD

**Issue by lepolau** [jgraph/drawio-desktop#889] opened 2022-01-26 16:09 UTC
* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The configuration change is not saved and does not seem to be taking into consideration after restarting draw.io desktop 16.4.0 (windows 64 msi installer or exe intaller).
When I modify it for example by adding :
"{
  "defaultFonts": [
    "Helvetica",
    "Liberation sans",
    "Arial",
    "Carlito",
    "Calibri",
    "Cambria",
    "Caladea",
    "Liberation serif"
  ],
  "maxImageBytes": 1000000000000,
  "maxImageSize": 1000000000000
}
"
that I click on apply, it does not appear anymore when trying to reopen the menu or after a restart. The box remains white.

**To Reproduce**
1. Go to 'Suppléments'
2. Click on 'Configuration'
3. Modify the configuration with
{
  "defaultFonts": [
    "Helvetica",
    "Liberation sans",
    "Arial",
    "Carlito",
    "Calibri",
    "Cambria",
    "Caladea",
    "Liberation serif"
  ],
  "maxImageBytes": 1000000000000,
  "maxImageSize": 1000000000000
}
4. click to Appliquer"

**Expected behavior**
 it does not appear anymore when trying to reopen the menu or after a restart. The box remains white.
The configuration change is not saved and does not seem to be taken into account after restarting draw.io desktop.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 16.4.0

**Desktop (please complete the following information):**
 - OS: Windows 64 bits msi or exe installer

**Comment by saf-dmitry** [comment] 2022-01-27 15:12
Possibly related to #873.

**Comment by davidjgraph** [comment] 2022-01-27 20:49
Duplicate of #873

**Closed as completed by davidjgraph** 2022-01-27 20:49 UTC
