### ISSUE TITLE
Drawio takes alot of extra memory 

### ISSUE THREAD

**Issue by OmarBoshra** [jgraph/drawio-desktop#481] opened 2021-01-27 21:46 UTC
![image](https://user-images.githubusercontent.com/47230931/106058202-3a834b80-60f1-11eb-97c4-3b14925fdc81.png)

Not only does it take so much memory it ,sometimes it keeps increasing until a crash happens

**Comment by mararad** [comment] 2021-01-28 09:34
Duplicate of https://github.com/jgraph/drawio-desktop/issues/431

**Closed** 2021-01-28 09:34 UTC
