### ISSUE TITLE
draw.io Desktop for macOS doesn't start anymore

### ISSUE THREAD

**Issue by yant831** [jgraph/drawio-desktop#1008] opened 2022-05-19 03:39 UTC
Hi，
I installed draw.io v18.0.6 on macOS (v10.14.6),  when I open the application,  no respone。 
Has anyone already encountered this issue? 

Best regards,
Yant

**Comment by JerryMWeeks** [comment] 2022-05-19 07:00
And in Windows 10 it hangs for ages loading, then ages when clicking on "New Diagram" and once new diagram is opened the left hand menu of items is also not clickable or loadable to canvas.
Might be a security update on my machine, if not, drawio has become unusable.

**Comment by davidjgraph** [comment] 2022-05-19 12:22
@JerryMWeeks https://github.com/jgraph/drawio-desktop/issues/944

**Comment by JerryMWeeks** [comment] 2022-05-20 13:18
@davidjgraph  not sure why you marked my comment off topic! As far as I can tell it is highly likely related.
Several people I work with have hit the same. DrawIO 18.0.6 hangs on loading, eventually does load, then you cannot click new diagram, after 4-10 minutes you can click new diagram, then you cannot click on widgets for another 4-10 minutes, then you cannot scroll widgets for another 4-10 minutes. 
I have rolled back to the last of the 17. version, and it immediately works fine. (I didn't suffer the #944 issue on 17. And my install of 17. is 100% fine and as ever excellent! :) 
As far as I can tell from your code it is by and large system agnostic, so it is imho feasible the @yant831 's problem is being caused by the same issue.
I also tried the "No Installer version" it behaves the same way:
here - after 2 minutes - overlay on this issue (the transparent grey box frame is the slow load)
If I push it windows responds in its helpful way...
And as of submitting this comment - a few minutes later it still hasn't loaded.
A Mac probably doesn't permit it to even do that much.
Oddly starting 18 has caused the running instance of 17 to freeze - if that helps.
![image](https://user-images.githubusercontent.com/19207251/169495132-003aea56-0671-491c-93ed-838483f2d504.png)
![image](https://user-images.githubusercontent.com/19207251/169495351-54917997-0f81-4933-ac95-f47f4aa28647.png)

**Comment by davidjgraph** [comment] 2022-05-20 13:41
@JerryMWeeks So you don't have windows defender read-time analysis running?

**Comment by JerryMWeeks** [comment] 2022-05-20 13:49
@davidjgraph  - yes, cannot turn it off: 
![image](https://user-images.githubusercontent.com/19207251/169542063-3719c096-911e-4169-b17f-5946d24a91c9.png)

**Comment by davidjgraph** [comment] 2022-05-20 13:58
@JerryMWeeks Look towards the bottom of 944, a user describes which directories to add exceptions for.

**Comment by davidjgraph** [comment] 2022-05-20 14:51
Closing issue, template not filled.

**Comment by JerryMWeeks** [comment] 2022-05-20 14:52
17 works fine for me though, and in all honesty, although the fix works, it is a hack - if some wise guy got hold of an installer on Sorin's machine a nasty surprise could be planted into the mentioned drawio folders.
Why does 17.4.2 work 100% okay on my machine? It loads in seconds.

![image](https://user-images.githubusercontent.com/19207251/169554579-2b9fa66b-9073-4291-9791-ed81e6e3930e.png)

**Closed as completed by davidjgraph** 2022-05-20 14:51 UTC
Labels: issue template not filled

**Comment by JerryMWeeks** [comment] 2022-05-20 14:54
@davidjgraph - I noticed you closed this issue - should I raise a new one?

**Comment by davidjgraph** [comment] 2022-05-20 15:05
Yes please. We require the issue template is filled on my new tickets to save us asking all the usual questions, otherwise the issue is closed.

If you issue is Windows Defender then your comments are off-topic for this thread, since the original post is regarding MacOS.
