### ISSUE TITLE
text background color unusable 14.9.6

### ISSUE THREAD

**Issue by ll3141** [jgraph/drawio-desktop#694] opened 2021-09-08 05:56 UTC
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
the "Background Color" checkbox in the Text tab of the format panel can't be checked

**To Reproduce**
1. create new document
2: place a text
3: with the text selected click the "Background Color" checkbox
4: on mouse button release, the checkbox gets checked and the color selector appears momentarily, but go back to unchecked/not visible immediately

**Expected behavior**
checkbox gets checked, color selector stays visible/usable

**Screenshots**
static screenshots are of no use in this case. If neccessary I could try to produce a screen recording

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 14.9.6]

**Desktop (please complete the following information):**
 - OS: windows 10.0.19042

**Additional context**
the same applys to texts in shapes too,
texts on connectors work though

**Comment by davidjgraph** [comment] 2021-09-09 11:34
Could you re-test in 15.1.3 please?

**Comment by ll3141** [comment] 2021-09-10 05:19
no change with 15.1.3

as with 14.9.6, I can add "labelBackgroundColor=..." to the style manually with the result that the "Background Color" check box will check and the color selector shows up.
Unchecking the checkbox works, but can't be check again.

**Comment by davidjgraph** [comment] 2021-09-10 05:57
Duplicate of https://github.com/jgraph/drawio/issues/2238

**Closed as completed by davidjgraph** 2021-09-10 05:57 UTC
