### ISSUE TITLE
Missing font in file brwoser

### ISSUE THREAD

**Issue by kmunoz99** [jgraph/drawio-desktop#886] opened 2022-01-25 16:11 UTC
### the bug
Whenever a file browser dialog is opened, the font is missing and shows only squares

### Steps to reproduce the behavior:
1. Go to File
2. Click on Save 

**Screenshots**
![image](https://user-images.githubusercontent.com/10671302/151012795-bb35abe3-282b-4393-8ee0-d53507e864af.png)

- draw.io version 16.4.0
 - OS: Fedora 34
 - GTK in X11
 - Window Manager: GNOME, also happens with i3-wm.
 - Only happens when installing from snap, the rpm works fine

**Comment by davidjgraph** [comment] 2022-01-25 16:32
Duplicate of #368

**Closed as completed by davidjgraph** 2022-01-25 16:32 UTC
