### ISSUE TITLE
Autosave should be opted out by default

### ISSUE THREAD

**Issue by giner** [jgraph/drawio-desktop#588] opened 2021-05-19 14:09 UTC
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
When working on a desktop it is normal scenario where you open a diagram, move things around intentionally or unintentionally and close the file without saving. It was quite a surprise when I found all my files which I played with were not in the original state any more. After a while I have realized that there is `autosave` option and it is enable by default.

**Describe the solution you'd like**
`autosave` option on the desktop app should be either disabled by default or alternatively user should be prompted on the first start whether he wants this option to be enabled or not. This would match a desktop user expected behaviour.

**Comment by wmjordan** [comment] 2021-09-22 07:08
How to disable this autosave behavior?

It makes me feel very unsafe and there's even no way to turn it off!
Any accidental changes are automatically applied to the file without my acknowledge.

A kid touched my works and closed the draw.io... OMG, my hours' work!!

**Comment by davidjgraph** [comment] 2021-11-29 16:06
Duplicate of #377

**Closed as completed by davidjgraph** 2021-11-29 16:06 UTC
