### ISSUE TITLE
Deleting layer freezes application (desktop and online)

### ISSUE THREAD

**Issue by SpikyClip** [jgraph/drawio-desktop#1212] opened 2023-01-14 05:00 UTC
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
When trying to delete a layer, clicking the delete button freezes the app, making the user unable to interact with anything (buttons, tabs, menus, moving objects) requiring the application to be ended with task manager. This can also be replicated in the [browser](https://app.diagrams.net).

**To Reproduce**
1. Open layers tab.
2. Create a new layer.
3. Create a new object.
4. Delete the new layer.
5. Application freezes.

Note: I noticed I can only replicate this issue if there is an object on the layer. If there is no object the layer is deleted with no issues.

**Expected behavior**
The layer should be deleted and the application should not be frozen.

**Screenshots**
I don't think a screenshot will really help here, the app is frozen and there is no error message.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.8.1 (web) and 20.7.4 (desktop)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home (22H2, 19045.2486)

**Additional context**
No additional context, I've never used layers before in this app so its the first time I've noticed this bug.

**Comment by SpikyClip** [comment] 2023-01-14 05:11
After some testing, it seems that the only way to delete a layer without freezing it is to delete all the elements in the layer first, before deleting the layer itself.

**Comment by mararad** [comment] 2023-01-19 16:02
Thanks for the report. I reproduced the issue in Chrome, Chrome Incognito and Firefox Win 10 Pro.
Also in desktop 20.7.4

https://user-images.githubusercontent.com/44292306/213491786-e20e9d49-71c0-4202-a3e0-fbf06526389a.mp4

**Comment by m-mohamedin** [comment] 2024-01-05 21:12
Is this still an issue in the latest version, I cannot reproduce?

**Comment by SpikyClip** [comment] 2024-01-09 03:50
No longer able to reproduce on desktop (22.1.16), however I am still able to reproduce it on web (20.8.5).

**Comment by davidjgraph** [comment] 2024-01-09 08:01
Thanks for the update. Closing as fixed as the latest version does not display the problem.

**Closed as completed by davidjgraph** 2024-01-09 08:01 UTC
Labels: Waiting for response
