### ISSUE TITLE
Plugin shapes not showing up

### ISSUE THREAD

**Issue by jdstuart** [jgraph/drawio-desktop#180] opened 2019-11-08 03:37 UTC
I use a C4 which is a template for a bunch of images. The plugin is hosted at https://tobiashochguertel.github.io/c4-draw.io/c4.js.

When starting draw.io desktop version it prompts to make sure I want to run the plugin. After selecting Ok, draw.io starts, but the shapes never show up on the left. They're also not shape set I can select from the "More shapes" dialog.

I don't know where to find logs for the application. How do I troubleshoot to provide more information?

I'm using `v12.2.2`

**Comment by davidjgraph** [comment] 2019-11-08 17:35
Duplicate of https://github.com/jgraph/drawio-desktop/issues/139

**Closed by davidjgraph** 2019-11-08 17:35 UTC
