### ISSUE TITLE
Fail local fonts

### ISSUE THREAD

**Issue by WHK102** [jgraph/drawio-desktop#417] opened 2020-10-30 23:38 UTC
### Enviroment

OS: Ubuntu 20.04 LTS
Installed via: Snapd
Version: 

```
$ snap info drawio
name:      drawio
summary:   draw.io desktop
publisher: draw.io (jgraph✓)
store-url: https://snapcraft.io/drawio
contact:   support@draw.io
license:   unset
description: |
  draw.io Desktop packaged for snap. https://github.com/jgraph/drawio-desktop
commands:
  - drawio
snap-id:      84JReQ8pcNGJyAbT0gSDiW7OpDkrdaXp
tracking:     latest/stable
refresh-date: 9 days ago, at 14:16 -03
channels:
  latest/stable:    13.7.9 2020-10-21 (60) 96MB -
  latest/candidate: ↑                           
  latest/beta:      ↑                           
  latest/edge:      12.6.5 2020-02-19 (11) 87MB -
installed:          13.7.9            (60) 96MB -
```

### Problem

After two days of installing the application, the detection of the use of fonts begins to fail. This does not happen with other applications that are also installed via snapd such as libreoffice.

The Proof:

- https://i.ibb.co/6RgBbyM/Captura-de-pantalla-de-2020-10-30-20-27-40.png
- https://i.ibb.co/hWBRk04/Captura-de-pantalla-de-2020-10-30-20-27-57.png

**Comment by Narcha** [comment] 2021-01-21 12:45
same issue.
OS: Manjaro Linux
installed via snap
Fonts only missing in the file picker.

**Comment by davidjgraph** [comment] 2021-01-21 12:54
Duplicate of #368

**Closed by davidjgraph** 2021-01-21 12:54 UTC
